// Static blog content — no CMS/backend. Each post's `sections` is a small
// array of { h2 } or { p } blocks, rendered in order by BlogPost.jsx.
// Add a new post by appending here; Blog.jsx and the sitemap read from this
// array, so a new post needs no other wiring besides a sitemap/brain entry.
export const POSTS = [
  {
    slug: 'gold-silver-ratio-explained',
    title: 'The Gold-Silver Ratio Explained (And Why It Moves)',
    description: 'What the gold-silver ratio actually measures, why it swings so much more than either metal alone, and how to read it without over-relying on it.',
    date: '2026-08-15',
    readTime: '6 min read',
    relatedPath: '/gold-vs-silver-investment',
    relatedLabel: 'Compare gold vs silver as an investment',
    updated: '2026-08-15',
    category: 'Metals',
    keywords: ['gold silver ratio', 'gold silver ratio today', 'gold silver ratio meaning', 'gold silver ratio calculator'],
    faqs: [
      { q: 'What is the gold-silver ratio today?', a: 'It changes constantly with live spot prices — MetalCalc shows the current ratio on the Gold vs Silver Investment guide, computed from live gold and silver spot prices.' },
      { q: 'Is a higher gold-silver ratio good or bad?', a: "Neither on its own — a high ratio has sometimes been read as silver being cheap relative to gold, but it's a data point, not a timing signal, and can stay elevated for years." },
      { q: 'What has the gold-silver ratio been historically?', a: "It has swung widely across different economic eras, driven by changing monetary and industrial-demand dynamics for each metal — there's no single 'normal' level it reverts to on a fixed schedule." },
      { q: 'Can I calculate the gold-silver ratio myself?', a: 'Yes — divide the current spot price of gold per ounce by the spot price of silver per ounce. MetalCalc does this automatically using live prices.' },
      { q: 'Does the ratio affect jewelry prices?', a: 'Not directly — jewelry pricing depends on the purity and weight of the specific metal used plus making charges, not the ratio between two different metals.' },
    ],
    sections: [
      { p: "If you've ever heard someone say \"the gold-silver ratio is at 80 right now\" and had no idea what that meant, here's the plain version: it's just gold's price divided by silver's price. Nothing more exotic than that. If gold is trading at $2,000 per troy ounce and silver is trading at $25 per ounce, the ratio is 2,000 ÷ 25 = 80. In plain English, that means it currently takes 80 ounces of silver to buy the same amount of money as one ounce of gold." },
      { h2: 'Why does anyone track this at all?' },
      { p: "Because gold and silver don't move together the way you might expect two \"precious metals\" to. If you watch their prices side by side for a few months, you'll notice silver jumps around a lot more — bigger rallies, bigger drops, more day-to-day noise. The gold-silver ratio is just a simple way of putting a number on that relationship, so instead of eyeballing two separate price charts, you get one number that tells you how the two are moving relative to each other." },
      { h2: "Why don't gold and silver move in lockstep?" },
      { p: "Gold is mostly a \"store of value\" asset — a thing people and central banks hold onto specifically because they expect it to hold its worth, especially when currencies or the broader economy look shaky. Very little gold actually gets used up in factories; most of it just sits in vaults, bars and jewelry. Silver is different. Yes, people invest in it the same way they invest in gold, but a meaningful chunk of silver demand comes from actual industrial use — electronics, solar panels, medical equipment, and more. That means silver's price reacts to two different forces: the same investor sentiment that moves gold, plus how the manufacturing/industrial economy is doing. Two demand drivers instead of one is exactly why silver swings harder in both directions — it can rally further than gold when things are good, and fall further when they're not." },
      { h2: 'What does a "high" or "low" ratio actually tell you?' },
      { p: "You'll sometimes see people say a high ratio means \"silver is cheap relative to gold,\" or a low ratio means \"gold is cheap relative to silver.\" That's a real, commonly discussed way of reading it — some traders use an extreme reading as a rough cue to shift some of their gold into silver, or vice versa, expecting the ratio to eventually move back toward a more typical level. Here's the important caveat though: this is not a precise trading signal with a guaranteed turning point. There is no fixed number where the ratio is \"supposed\" to sit, and it has stayed at unusually high or low levels for years at a stretch before reversing. Treat an extreme reading as one useful data point to factor into a bigger decision — not a rule that tells you exactly when to act." },
      { h2: 'What actually pushes the ratio up or down, day to day?' },
      { p: "A few forces do most of the work. When markets get nervous — a recession scare, a geopolitical shock, a currency wobbling — money tends to flow into gold faster than into silver, because gold is seen as the safer, more established \"panic button\" asset. That pushes the ratio up. On the flip side, when manufacturing and industrial demand are strong, silver often catches a bid that gold simply doesn't get, which pushes the ratio back down. Currency strength and real interest rates (the interest rate minus inflation) affect both metals, but rarely by exactly the same amount, which is part of why the ratio is never perfectly stable." },
      { h2: 'How to actually use the ratio if you own metals' },
      { p: "If you're trying to decide how to split money between gold and silver, the ratio is a reasonable extra input — not the entire decision. Pair it with two more personal questions: how easily do you need to be able to sell what you own (gold generally resells more easily almost everywhere in the world), and how much day-to-day price swing can you actually tolerate without it bothering you (silver will test that more than gold will). MetalCalc shows you the live, up-to-the-minute ratio on the Gold vs Silver Investment guide, so you're never working from a stale number." },
      { h2: 'A simple way to put this into practice' },
      { p: "You don't need to become a full-time trader to get value from this. A practical approach: check the live ratio occasionally when you're thinking about adding to your metals, note roughly where it sits compared to what you've seen over the past year or two, and let that nudge — not dictate — whether you lean a little more toward gold or silver on that particular purchase. Then track what you actually hold. My Holdings lets you log both metals together and shows a diversification score, so you can see in one place whether your real-world split matches what you intended, instead of just remembering a vague sense of \"I think I own more gold than silver.\"" },
    ],
  },
  {
    slug: 'zakat-on-gold-with-examples',
    title: 'How Zakat on Gold Is Actually Calculated (With Worked Examples)',
    description: 'A plain-language walkthrough of the nisab threshold, the 2.5% rate, and two full worked examples for gold and mixed metal holdings.',
    date: '2026-08-22',
    readTime: '5 min read',
    relatedPath: '/zakat',
    relatedLabel: 'Use the Zakat Calculator',
    updated: '2026-08-22',
    category: 'Metals',
    keywords: ['zakat calculator', 'zakat calculator on gold', 'zakat calculator for gold in indian rupees', 'zakat calculator on silver'],
    faqs: [
      { q: 'How much zakat do I pay on gold?', a: '2.5% of the qualifying value — not the weight — once your total zakatable holdings cross the nisab threshold and have been held a full lunar year.' },
      { q: 'What nisab threshold should I use for gold zakat?', a: 'Most contemporary scholars recommend the silver-based nisab (595g of silver value) when assessing zakat on mixed gold/cash holdings, since it is the lower, more inclusive threshold.' },
      { q: 'Do I pay zakat on gold jewelry I wear?', a: "This is a genuinely debated point across schools of thought, not a math question — some hold all gold is zakatable regardless of use, others exempt personal-use jewelry. Decide with your own scholar; the calculator computes the number either way." },
      { q: 'Is zakat calculated on gold weight or gold value?', a: 'Value — convert your weight and purity to a currency value at the current spot price first, then apply the 2.5% rate to that value.' },
      { q: 'Can I calculate zakat on gold in Indian Rupees?', a: 'Yes — MetalCalc lets you pick your display currency (including INR) and applies the live exchange rate automatically before computing the nisab comparison and zakat due.' },
    ],
    sections: [
      { p: "If you own gold or silver and want to know whether you owe zakat on it, here's the short version before we get into the detail: zakat becomes due once the value of your qualifying holdings crosses a minimum threshold (called the nisab) and you've held that value for a full lunar year (roughly 354 days — a little shorter than a regular calendar year, since the Islamic calendar is lunar). Once you're above that threshold, the rate itself is simple and fixed: 2.5% of the value — not the weight." },
      { h2: 'What is "nisab," in plain terms?' },
      { p: "Nisab is just the minimum amount of wealth you need to have before zakat applies to you at all — think of it as a floor. If what you own is worth less than the nisab, you don't owe anything that year, no matter how long you've held it. There are two traditional ways to set this floor for precious metals: one based on a gold weight (85 grams), and one based on a silver weight (595 grams). Here's the part that surprises people: most contemporary scholars recommend using the silver-based nisab even when you're mainly dealing with gold or cash, because silver's value is lower than gold's, which makes the silver nisab the lower, more inclusive threshold. A lower threshold means more people end up qualifying to pay zakat — which is actually the intent of zakat as a form of charitable redistribution, not a loophole to minimize what's owed. MetalCalc's Zakat Calculator uses the silver nisab by default for exactly this reason." },
      { h2: 'Worked example 1: you clearly owe zakat' },
      { p: "Say you own 50 grams of 22-karat gold. Checking today's live silver nisab threshold (595 grams of silver, converted into your currency at today's rate), it works out to roughly $450. Your 50 grams of 22k gold, at today's gold price, happens to be worth $2,800. Since $2,800 is comfortably above the $450 nisab threshold, zakat is due on it: $2,800 × 2.5% = $70 owed." },
      { h2: 'Worked example 2: you\'re below the threshold, so nothing is due' },
      { p: "Now say instead you own a much smaller amount — 5 grams of 18-karat gold, worth roughly $250 — and you have no other zakatable cash or assets to add to it. The silver nisab threshold is still $450. Since your $250 is below that $450 floor, no zakat is due this year on that holding. You're simply under the minimum, and that's a completely normal, common situation — most people's day-to-day jewelry sits well under nisab on its own." },
      { h2: 'The one genuinely debated question: does jewelry you wear count?' },
      { p: "This is worth being upfront about: whether jewelry you actually wear day-to-day (as opposed to gold just sitting in a drawer as savings) counts toward zakat is a real point of disagreement across different schools of Islamic thought. Some scholars hold that all gold and silver is zakatable regardless of whether you wear it or not. Others exempt personal-use jewelry within reasonable limits, reasoning that it's functionally clothing, not savings. This is a religious ruling question, not a math question — MetalCalc's calculator will compute the number either way you decide, but deciding which rule to follow is between you and your own scholar or school of thought, not something a calculator can settle for you." },
      { h2: 'How to actually check your own number' },
      { p: "Manually tracking the live silver nisab threshold and converting your own gold/silver weight and purity into today's value is tedious to do by hand, and the nisab threshold itself moves daily as silver's price moves. The Zakat Calculator does this for you — enter your gold and/or silver holdings (weight, purity, and which currency you think in), and it fetches the current silver nisab threshold and applies the 2.5% rate automatically, so you're always working from today's real numbers instead of a stale estimate." },
    ],
  },
  {
    slug: 'gold-loan-vs-personal-loan',
    title: 'Gold Loan vs Personal Loan: Which Is Actually Cheaper?',
    description: "A structural comparison of gold-backed loans and unsecured personal loans — rates, speed, risk, and when each one actually makes sense.",
    date: '2026-08-29',
    readTime: '5 min read',
    relatedPath: '/loan-against-gold',
    relatedLabel: 'Estimate your gold loan amount',
    updated: '2026-08-29',
    category: 'Metals',
    keywords: ['gold loan interest rate', 'gold loan interest rate calculator', 'gold loan interest rates in sbi', 'gold loan interest rates in hdfc'],
    faqs: [
      { q: 'Why are gold loan interest rates lower than personal loans?', a: "Gold loans are secured by collateral, so the lender's risk is capped at the pledged gold's value — that lower risk is usually priced as a lower rate than an unsecured personal loan." },
      { q: 'What is LTV in a gold loan?', a: "Loan-to-value — the maximum percentage of the gold's current market value a lender will advance as a loan, commonly in the 60-75% range depending on the lender and local regulation." },
      { q: 'What happens if gold prices fall after I take a gold loan?', a: 'Some lenders can ask you to pledge additional gold or repay part of the loan to stay within the agreed LTV cap — this is the main structural risk a personal loan does not carry.' },
      { q: 'Do gold loan interest rates vary by bank?', a: 'Yes, significantly — rates differ by lender (banks vs NBFCs), loan tenure, and LTV chosen. Compare the specific rate your lender quotes against your own estimated loan amount before deciding.' },
      { q: 'How is the loan amount against gold calculated?', a: "Qualifying gold value (weight × purity × live spot price) multiplied by the lender's LTV percentage — MetalCalc's Loan Against Gold calculator estimates this using live prices." },
    ],
    sections: [
      { p: "If you need cash in a hurry and you happen to own gold, you've probably wondered whether it's smarter to pledge that gold for a loan, or just take out an ordinary personal loan instead. Both get you money quickly, but underneath they work on completely different risk models — and understanding that difference is really what explains why one is usually cheaper than the other." },
      { h2: 'What makes a gold loan different in the first place' },
      { p: "A gold loan is what's called a \"secured\" loan — secured simply means you hand over something valuable (in this case, physical gold) as collateral, which the lender holds onto until you repay. Because the lender has that gold sitting with them as a backstop, their downside is capped at whatever that gold is worth, even in a worst case where you can't repay. A personal loan, by contrast, is \"unsecured\" — the lender is relying purely on your promise to pay and your credit history, with nothing physical backing it up if things go wrong." },
      { h2: 'Why that difference usually makes gold loans cheaper and faster' },
      { p: "Because the lender's risk is lower on a secured loan, they typically charge a lower interest rate for it than they would for an unsecured personal loan. On top of the rate advantage, gold loans tend to get approved much faster — often the same day — because the lender doesn't need to dig through your income history or credit score the way they do for a personal loan; the gold itself is doing most of the reassuring. Less paperwork, less waiting, usually a better rate." },
      { h2: "So why would anyone still choose a personal loan?" },
      { p: "A few real reasons. First, a personal loan doesn't require you to physically hand over an asset — there's no risk of losing gold you might have sentimental attachment to, and no logistics of depositing it somewhere and later retrieving it. Second, if your credit profile is genuinely strong, the rate gap between the two loan types can shrink quite a bit, making the convenience of not pledging an asset worth more to you. And third, plenty of people simply don't own enough gold to make pledging it a realistic option in the first place." },
      { h2: 'The one real risk a gold loan carries that a personal loan doesn\'t: the LTV squeeze' },
      { p: "Here's the part that catches some borrowers off guard. Lenders will only advance you a loan up to a certain percentage of your gold's current market value — this percentage is called the loan-to-value ratio, or LTV for short. It's commonly somewhere in the 60-75% range, though the exact number depends on the lender and local regulations. The catch: if gold prices drop noticeably after you've already taken the loan, your collateral is now worth less, and some lenders will ask you to either pledge additional gold to make up the difference, or repay part of the loan early to get back within the agreed LTV cap. This is a real structural risk unique to gold loans — a personal loan's terms don't move with the price of an unrelated asset, so you never get a similar surprise call there." },
      { h2: 'A simple way to decide between the two' },
      { p: "If you have gold sitting idle, need cash quickly, you're genuinely comfortable pledging it, and gold prices look stable or rising rather than falling, a gold loan usually wins on both rate and speed. On the other hand, if you'd rather not hand over an asset at all, your credit is strong enough that the rate gap barely matters, or you're nervous that a falling gold price could trigger an LTV call you're not prepared for, a personal loan avoids that specific risk — even if you end up paying a somewhat higher rate for that peace of mind." },
      { h2: 'Check your own numbers before deciding' },
      { p: "Rates and LTV limits vary meaningfully between lenders, so it's worth actually estimating what you'd get offered rather than guessing. The Loan Against Gold calculator takes your specific gold or silver holdings — weight, purity, and a loan-to-value percentage you choose — and estimates the loan amount a lender might offer, using live spot prices rather than a number you'd have to look up and plug in yourself." },
    ],
  },
  {
    slug: 'dollar-cost-averaging-crypto-does-it-work',
    title: 'Dollar-Cost Averaging Into Crypto: Does It Actually Work?',
    description: "What DCA actually does mathematically, when it helps vs a lump sum, and how to backtest it yourself against real price history.",
    date: '2026-09-02',
    readTime: '6 min read',
    relatedPath: '/crypto',
    relatedLabel: 'Try the DCA simulator on a real coin',
    updated: '2026-09-02',
    category: 'Markets',
    keywords: ['dollar cost averaging', 'dollar cost averaging calculator', 'dollar cost averaging vs lump sum', 'dollar cost averaging crypto'],
    faqs: [
      { q: 'Is dollar-cost averaging better than lump sum investing?', a: 'Mathematically, a lump sum slightly wins in a sustained uptrend since all capital is exposed from day one — DCA tends to do better in choppy or down-then-up markets, and its bigger advantage for most people is behavioral, not mathematical.' },
      { q: 'How does dollar-cost averaging work with crypto?', a: 'Same principle as any asset — invest a fixed amount on a fixed schedule regardless of price, which averages your cost basis across both dips and rallies instead of betting on one entry point.' },
      { q: 'Can I backtest dollar-cost averaging myself?', a: "Yes — MetalCalc's Crypto page has a DCA simulator per coin: pick an amount, frequency and lookback window, and it shows real total invested, current value, and gain/loss against that coin's actual price history." },
      { q: 'What is a good DCA frequency — daily, weekly or monthly?', a: 'There is no single correct answer; higher frequency slightly smooths entries further but the behavioral benefit of just staying consistent usually matters more than the exact interval chosen.' },
      { q: 'Does DCA guarantee a profit?', a: 'No — it manages entry-price risk, not market risk. If an asset declines over your whole buying window and never recovers, DCA does not protect you from that loss.' },
    ],
    sections: [
      { p: "Dollar-cost averaging (DCA) means investing a fixed amount on a fixed schedule — say $50 every week — regardless of price. The pitch is that it smooths out volatility by buying more units when price is low and fewer when it's high, without you having to time anything." },
      { h2: "What DCA mathematically does" },
      { p: "DCA lowers your average cost basis versus buying a large chunk right before a drop, and it removes the emotional problem of trying to pick a bottom. But it's not magic — your average buy price is still a weighted average of whatever prices occurred during your buying window. If an asset only goes up over that window, DCA very slightly underperforms a lump sum invested on day one, since some of your capital sits on the sidelines waiting for later buy dates instead of being invested from the start." },
      { h2: 'When DCA actually helps' },
      { p: "DCA does best in choppy, sideways-to-down-then-up markets — the volatility itself is what lets you accumulate units cheaply on the dips. In a strong, sustained uptrend with no real pullbacks, a lump sum on day one usually wins, because every dollar is exposed to the gains from the start." },
      { h2: "The behavioral case, separate from the math" },
      { p: 'Even when the math slightly favors a lump sum, many people never actually deploy a lump sum — they hesitate, wait for a "better" entry that may never come, and end up not investing at all. DCA\'s real advantage for a lot of people isn\'t mathematical, it\'s that it forces consistent participation.' },
      { h2: 'Backtest it yourself instead of trusting a rule of thumb' },
      { p: "Rather than assume DCA is good or bad in the abstract, test it against a specific coin's real price history. MetalCalc's Crypto page has a DCA simulator on any coin's detail panel — pick an amount, a frequency (daily/weekly/monthly), and a lookback window (up to 90 days, the free-tier cap on historical data), and it shows your actual total invested, current value, gain/loss, and how a lump-sum-on-day-one would have compared over that same window." },
    ],
  },
  {
    slug: 'peg-ratio-explained',
    title: 'PEG Ratio Explained: The Metric Behind Our Stock Rankings',
    description: "What PEG actually corrects for that P/E alone misses, how to read a PEG number, and its real limitations.",
    date: '2026-09-05',
    readTime: '5 min read',
    relatedPath: '/stocks',
    relatedLabel: 'See PEG-ranked stocks',
    updated: '2026-09-05',
    category: 'Markets',
    keywords: ['peg ratio', 'peg ratio meaning', 'peg ratio formula', 'peg ratio less than 1'],
    faqs: [
      { q: 'What is a good PEG ratio?', a: "Around 1.0 is the traditional rough benchmark for 'fairly valued relative to growth' — below 1 has historically been read as potentially undervalued, above 1 as potentially overvalued, but it's a heuristic, not a rule." },
      { q: 'What does PEG ratio less than 1 mean?', a: "It means the stock's P/E is lower than its earnings growth rate percentage — conventionally read as a sign the stock may be undervalued relative to how fast it's growing, though other factors (debt, cyclicality) still matter." },
      { q: "What is the formula for PEG ratio?", a: 'PEG = (Price / Earnings) ÷ EPS Growth Rate (%) — it divides the P/E ratio by the expected or trailing earnings growth percentage.' },
      { q: 'Is PEG ratio better than P/E ratio?', a: "PEG corrects a specific blind spot P/E has — it accounts for growth, so a high-growth and low-growth company become comparable on one scale. It's not strictly 'better', it answers a different question." },
      { q: 'What does a negative PEG ratio mean?', a: 'It usually means the company has negative earnings growth (shrinking earnings) or negative earnings altogether — a negative PEG is generally not a useful valuation signal and needs separate investigation into why growth is negative.' },
    ],
    sections: [
      { p: "PEG ratio is P/E ratio divided by expected earnings growth rate: PEG = (Price / Earnings) ÷ (EPS Growth %). It exists to fix a specific blind spot in P/E alone." },
      { h2: "The problem PEG fixes" },
      { p: 'A stock with a P/E of 30 looks expensive next to one with a P/E of 15 — until you notice the first one is growing earnings at 40% a year and the second at 5%. P/E alone can\'t tell you whether a "high" valuation is actually justified by growth. PEG folds growth into the same number, so a high-growth company and a low-growth company become comparable on one scale.' },
      { h2: 'How to read a PEG number' },
      { p: 'A PEG around 1.0 is the traditional rough benchmark for "fairly valued relative to growth" — below 1 has historically been read as potentially undervalued, above 1 as potentially overvalued or already pricing in future growth. This is a heuristic from Peter Lynch\'s writing, not a law — plenty of well-run companies trade above 1 for years because the market is willing to pay up for quality, predictability or a moat, not just raw growth.' },
      { h2: "What PEG doesn't capture" },
      { p: "It relies on a growth estimate — usually forward analyst estimates — which can be wrong, revised, or gamed by a single easy comparison quarter. It also doesn't account for debt load, margins, capital intensity, or cyclicality; a cyclical stock's PEG can look great right at the top of its cycle and terrible right at the bottom, for reasons that have nothing to do with the business getting better or worse." },
      { h2: 'How MetalCalc uses it' },
      { p: "The Stocks page's rankings table sorts by PEG among curated AI/Semiconductor/Tech names, and the Trade Signals section factors it alongside EPS/revenue growth YoY, 52-week range position, and momentum into one composite score — not PEG alone. It's one input in a multi-factor score, same caveat as everywhere else on this site: today's snapshot, not investment advice." },
    ],
  },
  {
    slug: 'position-sizing-101',
    title: 'Position Sizing 101: The Math That Keeps One Bad Trade From Wrecking Your Account',
    description: 'Fixed-fractional position sizing explained — how risking a set % per trade, not a set dollar amount, protects an account over many trades.',
    date: '2026-09-09',
    readTime: '5 min read',
    relatedPath: '/position-size',
    relatedLabel: 'Calculate your own position size',
    updated: '2026-09-09',
    category: 'Markets',
    keywords: ['position sizing calculator', 'position sizing formula', 'position sizing and risk management', 'position sizing calculator for stocks'],
    faqs: [
      { q: 'What is the formula for position sizing?', a: 'Position size = (Account size × Risk %) ÷ (Entry price − Stop-loss price). A wider stop automatically yields a smaller position at the same risk percentage.' },
      { q: 'How much should I risk per trade?', a: 'A common convention is 1-2% of account size per trade — small enough that a long losing streak still leaves most of the account intact to keep trading.' },
      { q: 'Does position sizing work for crypto and forex too?', a: 'Yes — the same fixed-fractional formula applies to any asset with a defined entry and stop-loss price, stocks, crypto or forex.' },
      { q: 'Why not just risk a fixed dollar amount per trade?', a: "A fixed percentage automatically scales down with the account after losses and up after gains, keeping risk proportional — a fixed dollar amount doesn't adjust and can become an outsized percentage after a losing streak." },
      { q: 'Should I increase position size after a loss to recover faster?', a: 'No — that increases risk exactly when the account cushion is already reduced. Recalculate position size off the current, smaller account balance instead.' },
    ],
    sections: [
      { p: "Most blown trading accounts don't die from one bad thesis — they die from betting too much on it. Position sizing is the part of risk management that has nothing to do with being right about a trade." },
      { h2: 'The core idea: risk a % of your account, not a fixed dollar amount' },
      { p: "Fixed-fractional position sizing means you decide upfront to risk a small, consistent percentage of your total account on any single trade — commonly 1-2% — regardless of how confident you feel. Position size is then derived from that percentage, your stop-loss distance, and your account size, not chosen first." },
      { h2: 'The formula' },
      { p: "Position size = (Account size × Risk %) ÷ (Entry price − Stop-loss price). A wider stop-loss automatically means a smaller position size at the same risk percentage — the math keeps risk constant even as your stop distance changes." },
      { h2: 'Why this matters more than being "right"' },
      { p: "A trader risking 1% per trade can be wrong 10 times in a row and still have roughly 90% of their account left to keep trading. A trader risking 20% per trade is functionally out of the game after 4-5 bad trades — even if their long-run win rate is identical. Survival, not any single trade's outcome, is what position sizing protects." },
      { h2: 'A common mistake this catches' },
      { p: "Doubling position size after a loss to \"win it back faster\" does the opposite of what fixed-fractional sizing is designed to do — it increases risk exactly when a string of losses has already reduced the account cushion. Recalculating position size off the current (smaller) account balance, not the size before the losses, is what keeps risk percentage actually constant." },
    ],
  },
  {
    slug: 'rsi-explained-overbought-oversold',
    title: 'RSI Explained: What Overbought and Oversold Actually Mean',
    description: 'How RSI is calculated, why 70/30 are the conventional thresholds, and the specific way it can mislead you in a strong trend.',
    date: '2026-09-10',
    readTime: '5 min read',
    relatedPath: '/crypto',
    relatedLabel: 'See live RSI on any coin\'s timeframe signals',
    updated: '2026-09-10',
    category: 'Markets',
    keywords: ['rsi indicator', 'rsi indicator meaning', 'rsi indicator buy and sell signals', 'rsi indicator strategy'],
    faqs: [
      { q: 'What does RSI above 70 mean?', a: "Conventionally labeled 'overbought' — the recent price move has been unusually one-sided to the upside over the lookback window. It's a momentum reading, not an automatic sell signal." },
      { q: 'What does RSI below 30 mean?', a: "Conventionally labeled 'oversold' — recent losses have dominated over the lookback window. Like overbought, it describes recent momentum, not a guaranteed reversal point." },
      { q: 'How is RSI calculated?', a: 'RSI compares the average size of up-moves to the average size of down-moves over a lookback period (commonly 14 candles), scaled to a 0-100 number.' },
      { q: 'Can RSI stay overbought for a long time?', a: 'Yes — in a strong sustained uptrend, RSI can sit above 70 for an extended stretch while price keeps climbing. Treating that as an automatic sell signal is a common mistake.' },
      { q: 'What is a good RSI trading strategy?', a: "RSI alone is rarely used as a sole signal — it's more reliable combined with trend/moving-average context and raw momentum, which is why MetalCalc's crypto timeframe signals blend all three into one verdict." },
    ],
    sections: [
      { p: "RSI (Relative Strength Index) measures the speed and size of recent price gains versus recent losses, scaled to a 0-100 number. It's one of the most widely used momentum indicators — and one of the most widely misread." },
      { h2: 'How it\'s actually calculated' },
      { p: "Over a lookback period (commonly 14 candles), RSI compares the average size of up-moves to the average size of down-moves. If gains have dominated, RSI trends toward 100. If losses have dominated, it trends toward 0. A reading of 50 means gains and losses have been roughly balanced over the period." },
      { h2: 'Why 70 and 30 are the conventional lines' },
      { p: "Above 70 is conventionally labeled \"overbought,\" below 30 \"oversold\" — meaning the recent move has been unusually one-sided in that window, not that the asset is objectively expensive or cheap. These thresholds are convention, not a law of markets; some traders use 80/20 for more volatile assets specifically because 70/30 triggers too often to be useful." },
      { h2: 'The trap: RSI in a strong trend' },
      { p: "In a strong, sustained uptrend, RSI can sit above 70 for a long stretch while price keeps climbing — treating that as an automatic sell signal has caused a lot of traders to exit a winning trend far too early. RSI describes recent momentum, not a guaranteed reversal point." },
      { h2: 'How it\'s used here' },
      { p: "MetalCalc's Crypto timeframe signals combine RSI with a moving-average crossover and raw momentum into one composite verdict per timeframe (15min through 3 months) — RSI alone never decides the signal, exactly because of the trend trap above." },
    ],
  },
  {
    slug: 'melt-value-vs-retail-price',
    title: 'Melt Value vs Retail Price: Why a Gold Chain Costs More Than Its Weight in Gold',
    description: 'What melt value actually measures, why retail price is always higher, and how to check the markup on a specific piece.',
    date: '2026-09-11',
    readTime: '4 min read',
    relatedPath: '/melt-check',
    relatedLabel: 'Check the markup on a specific piece',
    updated: '2026-09-11',
    category: 'Metals',
    keywords: ['melt value calculator', 'melt value calculator gold', 'melt value calculator silver', 'melt price calculator'],
    faqs: [
      { q: 'What is melt value?', a: "What a piece of jewelry would be worth if melted down to raw metal today — weight × purity × today's spot price, nothing else." },
      { q: 'How do I calculate melt value of gold jewelry?', a: "Multiply the item's weight by its purity fraction (e.g. 0.9167 for 22k) by the current spot price per gram. MetalCalc's Melt vs Retail tool does this automatically with live prices." },
      { q: 'Why is retail price always higher than melt value?', a: 'Making charges (design labor, wastage), retailer margin, and taxes all sit on top of melt value — real costs, not necessarily a scam.' },
      { q: 'What is a reasonable markup over melt value?', a: "There's no universal number — a simple machine-made band carries a small markup, while an intricate handmade or branded piece can reasonably carry a much larger one for the craftsmanship." },
      { q: 'Does melt value work for silver coins too?', a: 'Yes — the same weight × purity × spot price math applies to silver coins and bars, not just gold jewelry.' },
    ],
    sections: [
      { p: "Here's a question almost everyone who's bought gold jewelry has asked at some point: why does my gold chain cost so much more than what the gold inside it is actually worth? The answer starts with understanding two different numbers. Melt value is simply what a piece of jewelry would be worth if someone melted it down right now and sold it as raw metal — weight multiplied by purity multiplied by today's spot price, and nothing else. Retail price is what you actually hand over at the counter, and it's always higher than melt value. Understanding the gap between those two numbers is the whole point of this guide." },
      { h2: "What exactly makes up that gap?" },
      { p: "Three things, generally. First, making charges — the labor cost of actually shaping raw metal into a finished design, plus an allowance for the small amount of metal lost as waste during crafting. Second, the retailer's own profit margin, same as any business selling a product. Third, whatever taxes apply in your area. None of these three are inherently unfair or a sign you're being cheated — skilled labor and running a retail business are real costs that have to be paid for somehow. What this does mean, though, is that comparing a retail price to melt value only tells you how big the markup is — it doesn't by itself tell you whether that markup is fair for what you're getting." },
      { h2: 'Why the same gap looks so different from one piece to the next' },
      { p: "A simple, machine-stamped plain band is quick and cheap to manufacture, so it typically carries only a small markup over its melt value. Compare that to an intricate handmade design, a piece from a recognizable brand, or something set with gemstones — these can carry a markup many times larger than the metal's melt value, and that's not necessarily a rip-off. The extra money in those cases is paying for genuine craftsmanship, design time, brand reputation, and the stones themselves — none of which show up in a melt-value calculation, because melt value only ever measures the metal." },
      { h2: 'How to tell a reasonable markup from a questionable one' },
      { p: "There's no single universal percentage that counts as \"fair\" — that's genuinely not how this works, and anyone telling you there's one fixed acceptable number is oversimplifying. What's more useful is context: a high markup on a plain, simple design with no special craftsmanship being claimed is worth questioning and asking about directly. That exact same markup percentage on a detailed, branded, or gem-set piece might be entirely reasonable once you account for the actual work involved. The goal isn't to find a magic cutoff — it's to understand what you're specifically paying for before you decide if it feels worth it." },
      { h2: "A few everyday situations where this matters" },
      { p: "You're comparing two similar-looking chains from different jewelers and want to know which one is actually the better deal once design complexity is accounted for. You're selling old jewelry and want a realistic sense of what it's worth in melt terms before a buyer makes you an offer. You inherited a piece and want to separate \"what the gold is worth\" from \"what it would cost to replace.\" You're buying a gift and want to understand roughly how much of the price tag is metal versus craftsmanship, so you know what you're really paying for. In every one of these, knowing the melt value first gives you a real anchor to reason from, instead of just trusting a quoted number." },
      { h2: 'The one mistake worth avoiding' },
      { p: "Don't assume melt value and retail price should ever be close together — that expectation is simply wrong for anything beyond the plainest machine-made pieces, and treating any markup as suspicious will just lead to constant, unproductive frustration. The useful habit isn't rejecting markup; it's checking the actual number for a specific piece so you can judge it with real information instead of a vague gut feeling." },
      { h2: 'Check any specific piece yourself' },
      { p: "You don't need to do this math by hand. Enter the weight, purity and asking price into the Melt vs Retail Markup Checker, and it computes the exact markup percentage using today's live spot price — then you can decide for yourself, with the real number in front of you, whether the craftsmanship and design justify what you're being asked to pay." },
    ],
  },
  {
    slug: 'currency-exchange-margins-explained',
    title: 'How Currency Exchange Margins Quietly Cost You Money',
    description: 'What a "quoted rate" actually hides, how dealer margins work, and how to check the real spread against mid-market.',
    date: '2026-09-12',
    readTime: '4 min read',
    relatedPath: '/rate-check',
    relatedLabel: 'Check a quoted rate against mid-market',
    updated: '2026-09-12',
    category: 'Tools',
    keywords: ['currency exchange margin', 'mid-market exchange rate', 'fx margin calculator', 'exchange rate spread'],
    faqs: [
      { q: 'What is an FX margin?', a: "The difference between the mid-market exchange rate (the real, neutral rate) and the rate a dealer or bank actually quotes you — it's built into the rate itself, not shown as a separate fee." },
      { q: 'Why do airport money changers have bad exchange rates?', a: 'Convenience and captive customers mean weaker competitive pressure, so airport and hotel exchange counters typically carry the widest margins over mid-market.' },
      { q: 'How do I check if an exchange rate is fair?', a: "Compare the quoted rate against the live mid-market rate for the same currency pair at the same moment — the percentage difference is the real cost of the transaction." },
      { q: 'Does FX margin affect gold and silver prices?', a: "Yes — if you're paying in a foreign currency for metal, a bad FX margin compounds on top of the metal price premium, increasing your total cost beyond the metal itself." },
      { q: 'Is a bank transfer cheaper than a money changer?', a: 'Often yes — bank transfers and reputable online FX services tend to have tighter margins closer to true mid-market than walk-up currency counters, though this varies by provider.' },
    ],
    sections: [
      { p: "When a money changer or bank quotes you an exchange rate, it's rarely the actual mid-market rate you'd see on a live FX feed — there's a margin built in, and it's often not disclosed as a separate line item." },
      { h2: 'How the margin hides inside the "rate" itself' },
      { p: 'Unlike a fee, which shows up as a separate charge, an FX margin is baked directly into the exchange rate you\'re quoted. You\'re never shown "mid-market rate + fee" — you\'re shown one number, and the margin is invisible unless you compare it to the real mid-market rate yourself.' },
      { h2: 'Why the margin varies by channel' },
      { p: "Airport currency counters and hotel exchange desks typically carry the widest margins — high convenience, captive customers, low competitive pressure. Bank transfers and reputable online FX services tend to have tighter margins, closer to true mid-market." },
      { h2: 'How to actually check it' },
      { p: 'Compare the rate you\'re quoted against the live mid-market rate for the same currency pair at the same moment. The percentage difference is the real cost of that transaction — often more than any explicit "fee" the provider advertises.' },
      { h2: 'Use it for gold too' },
      { p: "This matters directly for metals: if you're paying in a foreign currency for gold/silver, a bad FX margin on top of the metal price compounds the total premium you're paying. The Exchange Rate Margin Checker compares any quoted rate against live mid-market to show the hidden spread." },
    ],
  },
  {
    slug: 'reverse-calculating-tax',
    title: 'Reverse-Calculating Tax: Finding the Base Price Hidden in a Tax-Inclusive Total',
    description: 'The formula for backing out base price and tax amount from a final tax-inclusive price, and where people get it wrong.',
    date: '2026-09-13',
    readTime: '3 min read',
    relatedPath: '/tax-reverse',
    relatedLabel: 'Reverse-calculate a tax-inclusive price',
    updated: '2026-09-13',
    category: 'Tools',
    keywords: ['gst reverse calculator', 'gst reverse calculator formula', 'reverse tax calculator', 'tax inclusive price calculator'],
    faqs: [
      { q: 'What is the formula to reverse calculate GST or tax?', a: 'Base price = Final price ÷ (1 + tax rate). For a 10% tax rate, divide by 1.10, don\'t subtract 10% from the final price — that gives a wrong answer.' },
      { q: 'Why can\'t I just subtract the tax percentage from the final price?', a: 'Because the tax rate applies to the base price, not the final price — subtracting it from the final price under-counts the actual base and tax amounts.' },
      { q: 'How do I find the tax amount from a final price?', a: 'First find the base price (final ÷ (1 + rate)), then subtract that from the final price — the difference is the tax amount.' },
      { q: 'Does this work for GST, VAT and sales tax?', a: 'Yes — the reverse-calculation math is the same for any percentage-based tax added on top of a base price, regardless of what the tax is called locally.' },
      { q: 'Why does this matter for jewelry bills?', a: "Jewelry bills often show one final number covering metal value, making charges and tax combined — reversing out the tax is the first step to seeing the metal value and making charges separately." },
    ],
    sections: [
      { p: "You're handed a final price that already includes tax, and you need to know the pre-tax base price and the tax amount separately — common with jewelry bills, invoices, and receipts that don't itemize." },
      { h2: 'The formula (and the common mistake)' },
      { p: "Base price = Final price ÷ (1 + tax rate). The mistake people make is subtracting the tax rate percentage directly from the final price instead of dividing — for a 10% tax rate, that means wrongly subtracting 10% of the final price instead of correctly dividing by 1.10. Those give different, and wrong, answers because the tax rate applies to the base price, not the final price." },
      { h2: 'Worked example' },
      { p: "Final price is $110, tax rate is 10%. Correct: base price = $110 ÷ 1.10 = $100, tax amount = $10. Incorrect: $110 − ($110 × 10%) = $99 — subtly wrong, and the error grows with higher tax rates." },
      { h2: 'Why this comes up so often with jewelry' },
      { p: "Jewelry bills frequently show one final number covering metal value, making charges and tax combined. Reverse-calculating the tax portion is the first step to then separating metal value from making charges — see the Jewelry Bill Breakdown tool for the fuller decomposition." },
    ],
  },
  {
    slug: 'what-diversification-score-measures',
    title: 'What a Diversification Score Actually Measures (and What It Doesn\'t)',
    description: 'The math behind an allocation-based diversification score, what a high or low number means, and its real blind spot.',
    date: '2026-09-14',
    readTime: '4 min read',
    relatedPath: '/net-worth',
    relatedLabel: 'See your own diversification score',
    updated: '2026-09-14',
    category: 'Markets',
    keywords: ['portfolio diversification calculator', 'portfolio diversification meaning', 'diversification score', 'portfolio diversification formula'],
    faqs: [
      { q: 'What is a diversification score?', a: 'A single number (commonly 0-100) summarizing how evenly your money is spread across asset classes — higher means more evenly spread, lower means more concentrated in one place.' },
      { q: 'How is a diversification score calculated?', a: "MetalCalc's uses the Herfindahl-Hirschman Index (HHI) — it sums the squared percentage share of each holding, which punishes concentration more harshly than a simple average would, then normalizes the result to 0-100." },
      { q: 'Does a high diversification score mean I am protected from losses?', a: "Not entirely — it only measures allocation spread, not whether your assets actually move independently of each other. Pair it with a correlation check for the full picture." },
      { q: 'What counts as well-diversified?', a: "There's no fixed cutoff, but a score closer to 100 means your capital is spread fairly evenly across the categories measured (e.g. metals, stocks, crypto), rather than concentrated in one." },
      { q: 'Can I see my own diversification score?', a: "Yes — MetalCalc's Net Worth page computes it automatically from your Holdings, Stock and Crypto portfolios." },
    ],
    sections: [
      { p: "A diversification score condenses \"how is my money spread across asset classes\" into one number. Here's what's actually inside it." },
      { h2: 'The math: Herfindahl-Hirschman Index (HHI)' },
      { p: "HHI sums the squared percentage share of each holding. Squaring means concentration is punished harder than the raw percentages suggest — a single asset at 100% scores far worse than the arithmetic gap to an even split would imply, because a 100% share squared is 1.0, dominating the sum. The score here is normalized to 0-100, so 100 means a perfectly even split across categories and 0 means everything in one." },
      { h2: 'What a high score tells you' },
      { p: "Your capital is spread evenly across the categories being measured (metals, stocks, crypto). It does not tell you those categories are uncorrelated, or that any individual position is well-chosen — it's purely about allocation spread." },
      { h2: 'The blind spot: correlation' },
      { p: "This is the important limit. An allocation score treats three asset classes as three independent bets by definition — but if all three move together on the same macro trigger (say, a broad risk-off event hitting stocks, crypto and even gold simultaneously in a liquidity crunch), a high allocation-diversification score doesn't protect you the way it implies. Pair it with an actual correlation check where one's available, like the crypto-only correlation tool on the Crypto page." },
      { h2: 'What to actually do with the number' },
      { p: "Treat it as one input on portfolio construction — flag heavy concentration in one asset class, but don't treat a high score alone as proof you're protected from a broad-based downturn." },
    ],
  },
  {
    slug: 'correlation-vs-diversification',
    title: "Correlation vs Diversification: Why Two Assets Can Both \"Diversify\" You and Still Crash Together",
    description: 'The difference between allocation-based diversification and correlation, and why you need both to actually reduce risk.',
    date: '2026-09-15',
    readTime: '4 min read',
    relatedPath: '/crypto',
    relatedLabel: 'Check correlation across your crypto watchlist',
    updated: '2026-09-15',
    category: 'Markets',
    keywords: ['portfolio diversification vs correlation', 'asset correlation meaning', 'crypto correlation', 'diversification mistake'],
    faqs: [
      { q: 'What is the difference between diversification and correlation?', a: 'Diversification measures how spread out your capital is across holdings. Correlation measures whether those holdings actually move independently of each other — you can have one without the other.' },
      { q: 'Can two assets be diversified but still correlated?', a: "Yes — a 50/50 split between two coins is perfectly allocation-diversified, but if both coins move the same direction on most days, a bad day for one is very likely a bad day for the other too." },
      { q: 'Why are crypto assets often highly correlated?', a: "A large share of crypto is driven by the same macro risk-on/risk-off sentiment and overall market liquidity — Bitcoin's mood pulls many altcoins with it regardless of each project's individual fundamentals." },
      { q: 'How do I check correlation between my crypto holdings?', a: "MetalCalc's Crypto page has a same-direction correlation check across your watchlist, showing what percentage of days each pair moved the same direction." },
      { q: 'Is high correlation always bad?', a: 'Not always — it just means those specific assets are not protecting you from each other in a downturn. Whether that matters depends on your overall goal for that part of the portfolio.' },
    ],
    sections: [
      { p: "You can be \"diversified\" by allocation and still own assets that move together almost every day. These are two different questions, and mixing them up is a common portfolio mistake." },
      { h2: 'Diversification (allocation) asks: how spread out is my capital?' },
      { p: "50% in one coin and 50% in another is, by allocation, perfectly even — a diversification score would read that as well-spread. It says nothing about whether those two coins actually behave independently." },
      { h2: 'Correlation asks: do these move together?' },
      { p: "A same-direction correlation check looks at the actual daily price history of two assets and measures what percentage of days they moved the same direction (both up or both down). Two coins can be perfectly allocation-diversified and still show 90%+ same-direction movement — meaning a bad day for one is very likely a bad day for the other too." },
      { h2: 'Why this happens so often in crypto specifically' },
      { p: "A large share of crypto assets are driven by the same macro risk-on/risk-off sentiment and overall market liquidity — Bitcoin's mood pulls a lot of altcoins with it regardless of each project's individual fundamentals. This is exactly why crypto portfolios that look diversified by coin count often aren't diversified by actual behavior." },
      { h2: 'Use both checks together' },
      { p: "An allocation score (Net Worth) tells you if your capital is spread out. A correlation check (Crypto watchlist tab) tells you if that spread actually behaves independently. High correlation with a high diversification score is the specific combination worth noticing — it means the spread is more cosmetic than protective." },
    ],
  },
  {
    slug: 'storage-and-insurance-hidden-cost',
    title: 'Storage and Insurance: The Hidden Carrying Cost of Holding Physical Metal',
    description: 'Why physical gold/silver isn\'t "free" to hold, what storage and insurance actually cost over time, and the break-even math.',
    date: '2026-09-16',
    readTime: '4 min read',
    relatedPath: '/storage-cost',
    relatedLabel: 'Estimate your own carrying cost',
    updated: '2026-09-16',
    category: 'Metals',
    keywords: ['gold storage insurance', 'gold storage costs', 'storage insurance cost', 'cost of storing gold'],
    faqs: [
      { q: 'How much does it cost to store gold safely?', a: 'It varies by method — a home safe is a one-time cost with limited insurability, while a bank safe deposit box or specialized depository charges an ongoing annual or monthly fee.' },
      { q: 'Does home insurance cover gold jewelry?', a: 'Often only up to a low cap — a serious gold/silver holding typically needs a supplemental insurance policy priced as a percentage of the insured value per year.' },
      { q: 'What is the break-even point for gold storage cost?', a: "If storage and insurance together cost 1% of your holding's value per year, your gold needs to appreciate more than 1% annually just to keep pace with that carrying cost." },
      { q: 'Is gold really free to hold?', a: "No — it doesn't pay a dividend or interest, and has a real ongoing storage/insurance carrying cost, unlike a balance in a brokerage app." },
      { q: 'Can I calculate my own gold storage cost?', a: "Yes — MetalCalc's Storage & Insurance Cost Calculator projects this cost over a chosen time horizon and shows the price appreciation needed to break even." },
    ],
    sections: [
      { p: "Here's something a lot of people don't think about until it's already an issue: physical gold doesn't pay you a dividend the way a stock might, doesn't earn interest the way a savings account does, and — unlike the number sitting in a brokerage app — actually costs real money to keep safe over time. We call this a \"carrying cost\": the ongoing expense of simply holding onto an asset, separate from whatever the asset itself is doing in price. It's an easy thing to forget when all you're looking at is a spot-price chart going up and to the right, but it's a real number that eats into your actual return." },
      { h2: 'What does it actually cost to store gold?' },
      { p: "There are a few common options, each with different tradeoffs. A home safe is a one-time purchase cost, but it comes with real limits — it's only as secure as your home itself, and it's usually much harder (or impossible) to get fully insured compared to professionally stored gold. A bank safe deposit box is more secure, but charges you an ongoing fee, usually billed annually or monthly. A specialized precious-metals depository (a dedicated facility built specifically for storing bullion) is the most secure option and also charges an ongoing fee, often scaled to either a flat rate or a percentage of the value you're storing." },
      { h2: "Insurance is a second, separate cost people often miss" },
      { p: "Here's the part that catches people off guard: your regular home insurance policy very likely does not fully cover your gold or jewelry. Most standard home policies cap jewelry and precious-metals coverage at a level far below what a serious holding is actually worth — sometimes just a few hundred dollars' worth, regardless of how much gold you actually own. If you own a meaningful amount, you'll typically need a separate, supplemental insurance policy specifically for it, priced as a percentage of the insured value per year, and that cost recurs every single year for as long as you keep holding the metal." },
      { h2: 'Putting storage and insurance together: the break-even question' },
      { p: "Here's why this matters for your actual returns, not just as trivia. If storage and insurance together cost a combined 1% of your holding's value per year, that means your gold needs to go up in price by more than 1% annually just to keep pace with what it's costing you to hold it — before you're genuinely ahead in real terms. To be clear, this doesn't make physical gold a bad idea at all. It just means the common assumption that \"gold is free to just sit there\" is wrong, and the real comparison you should be making is between your carrying cost and how much price appreciation you actually expect over the time you plan to hold it." },
      { h2: 'A concrete way to think about it' },
      { p: "Imagine you're holding $20,000 worth of gold, and your storage plus insurance together run you about $150 a year — roughly 0.75% of the holding's value. If gold happens to be flat that year, you haven't just \"broken even\" — you're actually down $150 in real terms once you account for that carrying cost. This is exactly the kind of number that's invisible if you only ever glance at a price chart, and exactly the kind of number worth knowing before you commit to a large long-term holding." },
      { h2: 'Run the actual numbers for your own situation' },
      { p: "Rather than estimating this in your head, the Storage & Insurance Cost Calculator projects your real carrying cost over whatever time horizon you choose, and shows you exactly how much price appreciation you'd need just to break even — turning a vague sense of \"gold is basically free to hold\" into an actual number you can plan around." },
    ],
  },
  {
    slug: 'alloy-mixing-math-explained',
    title: 'Alloy Mixing Math: What Happens When You Melt Two Different Purities Together',
    description: 'The weighted-average formula behind melting two gold/silver purities together, with a worked example.',
    date: '2026-09-17',
    readTime: '3 min read',
    relatedPath: '/alloy-mix',
    relatedLabel: 'Calculate your own blended purity',
    updated: '2026-09-17',
    category: 'Metals',
    keywords: ['alloy mixing calculator gold', 'gold alloy mixing ratio calculator', 'what alloys are mixed with gold', 'blended gold purity'],
    faqs: [
      { q: 'What happens when you melt 22k and 14k gold together?', a: "You get a weight-weighted blend of the two purities, not a simple average of the karat numbers — the heavier piece pulls the result closer to its own purity." },
      { q: 'What is the formula for blended gold purity?', a: "Blended purity = (weight1 × purity1 + weight2 × purity2) ÷ (weight1 + weight2) — a weight-weighted average of the purity fractions, not the karat numbers directly." },
      { q: 'What metals are commonly alloyed with gold?', a: 'Copper and silver are the most common alloy metals mixed with pure gold to adjust hardness, durability and color for jewelry use.' },
      { q: 'Can gold be mixed with platinum?', a: "They can technically be melted together, but platinum has a much higher melting point and very different properties, so this is unusual outside specific alloy formulations — most jewelry alloying is gold with copper/silver." },
      { q: 'Does mixing more than two purities get more complicated?', a: 'Yes — the same weighted-average math still applies across any number of pieces, but doing it by hand gets more error-prone the more pieces and purities you combine.' },
    ],
    sections: [
      { p: "Here's a very natural assumption that turns out to be wrong: if you melt a 22-karat piece of gold together with a 14-karat piece, you might expect to land somewhere in the middle, like 18-karat. That's not actually how it works. The real result depends not just on the two purities, but on how much each piece weighs relative to the other — and getting this wrong before melting down mixed-karat jewelry can mean ending up with a blend you didn't expect." },
      { h2: 'The actual formula, explained in plain terms' },
      { p: "The underlying math is what's called a weight-weighted average — meaning each piece's purity gets \"weighted\" by how much of the total weight it represents. The formula is: blended purity = (weight of piece 1 × purity of piece 1 + weight of piece 2 × purity of piece 2) ÷ (total combined weight). What this means practically is that a small amount of low-purity metal barely moves the final result if it's melted together with a much larger amount of high-purity metal — and the reverse is just as true the other way around. The heavier piece always pulls the result closer to its own purity." },
      { h2: 'A worked example, step by step' },
      { p: "Say you melt 10 grams of 22-karat gold (which has a purity fraction of 0.9167) together with 5 grams of 14-karat gold (purity fraction 0.5833). Plugging into the formula: (10 × 0.9167 + 5 × 0.5833) ÷ (10 + 5) = (9.167 + 2.9165) ÷ 15 ≈ 0.806. That blended purity of roughly 0.806 works out to approximately 19.3-karat equivalent — noticeably closer to the 22-karat piece than to the 14-karat one, simply because the 22-karat piece was twice the weight of the 14-karat piece." },
      { h2: "Why equal weights don't simply average the karat numbers either" },
      { p: "If you melted equal weights of 22k and 14k together, you might notice that averaging the karat numbers themselves (22 and 14, averaging to 18) happens to land close to what the purity-fraction math gives you in this particular case. That's a bit of a coincidence related to how karat numbers scale in a straight line up to 24 — it is not a reliable shortcut you can lean on generally. The real math is always done on purity fractions and actual weights, never on karat numbers directly, and the more pieces and purities you start combining, the more error-prone doing this by hand becomes." },
      { h2: 'Why this matters in practice' },
      { p: "This comes up any time you're combining mixed-karat scrap — old jewelry you're melting down together, broken pieces of different purities being recast into something new, or a jeweler quoting you a blended value for a mixed lot you're selling. If you (or whoever is melting it) assumes a simple average instead of doing the actual weighted calculation, the resulting purity estimate can be meaningfully off, especially when the pieces being combined are very different in weight." },
      { h2: 'Skip the manual math entirely' },
      { p: "Doing this arithmetic by hand gets tedious and error-prone fast, especially with more than two pieces. The Alloy Mixing Calculator takes any number of pieces, each with its own weight and purity, and computes the exact blended result for you — genuinely useful to check before melting down a mixed-karat batch of old jewelry or scrap." },
    ],
  },
  {
    slug: '52-week-range-demand-supply-proxy',
    title: "The 52-Week Range as a Demand/Supply Proxy: What It Can and Can't Tell You",
    description: 'Why position within the 52-week range is used as a stand-in for real support/resistance, and where that substitution breaks down.',
    date: '2026-09-18',
    readTime: '4 min read',
    relatedPath: '/stocks',
    relatedLabel: "See 52-week range position on ranked stocks",
    updated: '2026-09-18',
    category: 'Markets',
    keywords: ['52 week high low', '52 week high low stocks', '52 week high low indicator', '52 week range'],
    faqs: [
      { q: 'What does 52-week range position mean?', a: "Where today's price sits between the stock's lowest and highest price over the past year, as a percentage — 0% is at the yearly low, 100% is at the yearly high." },
      { q: 'How is 52-week range position calculated?', a: 'Range position = (current price − 52-week low) ÷ (52-week high − 52-week low), expressed as a percentage.' },
      { q: 'Is a stock near its 52-week low a buy signal?', a: "Not automatically — it can mean less recent selling pressure, or it can mean the stock is in a genuine decline with no support nearby. It's a rough proxy, not a reliable signal on its own." },
      { q: 'Why use 52-week range instead of real support and resistance?', a: 'Real support/resistance needs intraday price-action history showing a level actually held on prior tests — when that data is not available (like on Finnhub\'s free tier), 52-week range position is a coarser stand-in built from just two data points.' },
      { q: 'Should I trade based on 52-week high/low alone?', a: 'No — it works best combined with other factors like valuation and growth, which is why MetalCalc blends it with PEG and momentum into one composite score rather than using it alone.' },
    ],
    sections: [
      { p: "Real support/resistance analysis needs intraday price-action history — every touch, every rejection, every volume spike at a level. When that data isn't available, position within the 52-week high/low range is a common stand-in. It's a proxy, not the real thing, and the difference matters." },
      { h2: 'What it actually measures' },
      { p: "Range position = (current price − 52-week low) ÷ (52-week high − 52-week low), as a percentage. Near 0% means trading close to the yearly low; near 100% means close to the yearly high. That's the entire calculation — no volume, no number of times a level was tested, no order-flow data." },
      { h2: 'Why it\'s used as a demand/supply proxy at all' },
      { p: 'The logic: a price near its yearly low has, on average, faced less recent buying pressure, and a price near its yearly high has faced less recent selling pressure — a rough, indirect signal about where demand and supply might sit, built entirely from two data points (the high and the low) rather than the full price history in between.' },
      { h2: 'Where the substitution breaks down' },
      { p: 'A stock can sit at 15% of its range not because it is near support, but because it is in a genuine structural decline with no support nearby at all. A real support level needs to show it actually held on prior tests — the 52-week range alone cannot distinguish "cheap relative to its own year" from "falling for a reason."' },
      { h2: 'How to use it responsibly' },
      { p: "Treat range position as one input describing where today sits relative to the past year, not a prediction of where price bounces next. MetalCalc's stock rankings show it as one factor among several (PEG, growth, momentum) in a composite score — never the sole basis for a signal." },
    ],
  },
]

export function getPostBySlug(slug) {
  return POSTS.find((p) => p.slug === slug) ?? null
}
