// Static blog content — no CMS/backend. Each post's `sections` is a small
// array of { h2 } or { p } blocks, rendered in order by BlogPost.jsx.
// Add a new post by appending here; Blog.jsx and the sitemap read from this
// array, so a new post needs no other wiring besides a sitemap/brain entry.
export const POSTS = [
  {
    slug: 'gold-silver-ratio-explained',
    title: 'The Gold-Silver Ratio Explained (And Why It Moves)',
    description: 'What the gold-silver ratio actually measures, why it swings so much more than either metal alone, and how to read it without over-relying on it.',
    date: '2026-08-15',
    readTime: '6 min read',
    relatedPath: '/gold-vs-silver-investment',
    relatedLabel: 'Compare gold vs silver as an investment',
    sections: [
      { p: "The gold-silver ratio is simply the spot price of gold divided by the spot price of silver — how many ounces of silver it takes to buy one ounce of gold. If gold is $2,000/oz and silver is $25/oz, the ratio is 80." },
      { h2: 'Why the ratio moves so much' },
      { p: "Gold and silver don't move in lockstep. Gold is overwhelmingly a monetary/store-of-value asset — central banks hold it, investors buy it as a hedge, and its price is driven mostly by macro sentiment (rates, currency strength, geopolitical risk). Silver carries real industrial demand on top of that (electronics, solar panels, medical uses), so it reacts to both macro sentiment and industrial-cycle swings. That extra demand driver is also why silver tends to be more volatile in both directions — it can rally harder than gold in a bull run and fall further in a selloff." },
      { h2: 'What a high or low ratio "means"' },
      { p: "A historically high ratio has sometimes been read as silver being cheap relative to gold, and a low ratio as gold being cheap relative to silver. Some traders use extreme readings as a rough cue to rotate between the two metals. This is a real, widely-discussed pattern — but it's not a timing signal with a fixed threshold, and the ratio can stay at an extreme for years before reverting. Treat it as one data point, not a trading rule." },
      { h2: 'What actually drives the ratio short-term' },
      { p: "Risk-off macro events tend to push the ratio up (gold gets bought as a safe haven faster than silver does). Strong industrial/manufacturing demand tends to push it down (silver catches a bid gold doesn't get). Currency moves and real interest rates affect both, but not always by the same amount." },
      { h2: 'How to actually use it' },
      { p: "If you're deciding how to split a metals allocation, the ratio is a reasonable input, not the whole decision — pair it with your own liquidity needs (gold resells more easily almost everywhere) and volatility tolerance (silver swings harder). MetalCalc shows the live ratio and a fuller comparison on the Gold vs Silver Investment guide, and you can track your own metals split with a diversification score on My Holdings." },
    ],
  },
  {
    slug: 'zakat-on-gold-with-examples',
    title: 'How Zakat on Gold Is Actually Calculated (With Worked Examples)',
    description: 'A plain-language walkthrough of the nisab threshold, the 2.5% rate, and two full worked examples for gold and mixed metal holdings.',
    date: '2026-08-22',
    readTime: '5 min read',
    relatedPath: '/zakat',
    relatedLabel: 'Use the Zakat Calculator',
    sections: [
      { p: "Zakat on gold and silver is due once your holdings' value crosses a minimum threshold (nisab) and you've held them for a full lunar year. The rate is a flat 2.5% of the qualifying value — not the weight, the value." },
      { h2: 'Which nisab applies to gold?' },
      { p: "There are two traditional nisab thresholds — one based on gold weight (85g) and one based on silver weight (595g). Most contemporary scholars recommend using the silver-based nisab when zakat is being assessed on cash/mixed assets, because it's the lower threshold and is considered more protective of the poor (more people qualify to pay, which is the point of zakat). MetalCalc's Zakat Calculator uses the silver nisab by default for exactly this reason." },
      { h2: 'Worked example 1: gold only' },
      { p: "Say you hold 50 grams of 22k gold, and the live silver nisab threshold (595g of silver, converted to your currency at today's rate) works out to $450. If your 50g of 22k gold is worth $2,800 today, you're well above nisab, so zakat is due: $2,800 × 2.5% = $70." },
      { h2: 'Worked example 2: gold + cash, below nisab' },
      { p: "Say you hold 5 grams of 18k gold (worth roughly $250) and no other zakatable cash, while the silver nisab threshold is $450. Since $250 is below the $450 nisab, no zakat is due this year on that holding — you're under the threshold." },
      { h2: 'What counts toward the calculation' },
      { p: "Jewelry you actually wear is a genuinely debated point across schools of thought — some hold all gold/silver is zakatable regardless of use, others exempt personal-use jewelry within reasonable limits. This is a religious ruling question, not a math question, and MetalCalc's calculator computes the number either way — it's on you (or your scholar) to decide what to include." },
      { p: "For an exact, up-to-date number using live prices, use the Zakat Calculator — enter your gold/silver holdings and it applies the current silver nisab and 2.5% rate automatically." },
    ],
  },
  {
    slug: 'gold-loan-vs-personal-loan',
    title: 'Gold Loan vs Personal Loan: Which Is Actually Cheaper?',
    description: "A structural comparison of gold-backed loans and unsecured personal loans — rates, speed, risk, and when each one actually makes sense.",
    date: '2026-08-29',
    readTime: '5 min read',
    relatedPath: '/loan-against-gold',
    relatedLabel: 'Estimate your gold loan amount',
    sections: [
      { p: "Both let you borrow cash quickly, but they work on completely different risk models — and that's what drives the rate difference." },
      { h2: 'Why gold loans are usually cheaper' },
      { p: "A gold loan is secured — you hand over physical gold as collateral, so the lender's downside is capped at the collateral value. That lower risk usually means a lower interest rate than an unsecured personal loan, faster approval (often same-day, since there's no income/credit-history underwriting to do), and less paperwork." },
      { h2: 'Why personal loans still make sense sometimes' },
      { p: "A personal loan doesn't require you to give up an asset — no risk of losing gold you might not want to part with, no logistics of physically depositing it with a lender. If your credit profile is strong, the rate gap between the two can narrow a lot, and some borrowers simply don't have gold to pledge." },
      { h2: 'The real risk of a gold loan: the LTV squeeze' },
      { p: "Lenders cap gold loans at a loan-to-value (LTV) ratio — commonly somewhere in the 60-75% range of the gold's current market value, though this varies by lender and regulation. If gold prices fall significantly after you take the loan, some lenders can ask you to either pledge more gold or repay part of the loan to stay within the LTV cap. This is the main structural risk a personal loan doesn't have — a personal loan's terms don't change with an unrelated asset's price." },
      { h2: 'Quick decision guide' },
      { p: "Have idle gold, need cash fast, comfortable pledging it, and prices are stable-to-rising? Gold loan usually wins on rate and speed. Don't want to pledge gold, have strong credit, or gold prices are volatile enough that an LTV call worries you? A personal loan avoids that specific risk, even at a likely-higher rate." },
      { p: "Use the Loan Against Gold calculator to estimate what a lender might offer against your specific gold/silver holdings at a given LTV, using live prices." },
    ],
  },
  {
    slug: 'dollar-cost-averaging-crypto-does-it-work',
    title: 'Dollar-Cost Averaging Into Crypto: Does It Actually Work?',
    description: "What DCA actually does mathematically, when it helps vs a lump sum, and how to backtest it yourself against real price history.",
    date: '2026-09-02',
    readTime: '6 min read',
    relatedPath: '/crypto',
    relatedLabel: 'Try the DCA simulator on a real coin',
    sections: [
      { p: "Dollar-cost averaging (DCA) means investing a fixed amount on a fixed schedule — say $50 every week — regardless of price. The pitch is that it smooths out volatility by buying more units when price is low and fewer when it's high, without you having to time anything." },
      { h2: "What DCA mathematically does" },
      { p: "DCA lowers your average cost basis versus buying a large chunk right before a drop, and it removes the emotional problem of trying to pick a bottom. But it's not magic — your average buy price is still a weighted average of whatever prices occurred during your buying window. If an asset only goes up over that window, DCA very slightly underperforms a lump sum invested on day one, since some of your capital sits on the sidelines waiting for later buy dates instead of being invested from the start." },
      { h2: 'When DCA actually helps' },
      { p: "DCA does best in choppy, sideways-to-down-then-up markets — the volatility itself is what lets you accumulate units cheaply on the dips. In a strong, sustained uptrend with no real pullbacks, a lump sum on day one usually wins, because every dollar is exposed to the gains from the start." },
      { h2: "The behavioral case, separate from the math" },
      { p: 'Even when the math slightly favors a lump sum, many people never actually deploy a lump sum — they hesitate, wait for a "better" entry that may never come, and end up not investing at all. DCA\'s real advantage for a lot of people isn\'t mathematical, it\'s that it forces consistent participation.' },
      { h2: 'Backtest it yourself instead of trusting a rule of thumb' },
      { p: "Rather than assume DCA is good or bad in the abstract, test it against a specific coin's real price history. MetalCalc's Crypto page has a DCA simulator on any coin's detail panel — pick an amount, a frequency (daily/weekly/monthly), and a lookback window (up to 90 days, the free-tier cap on historical data), and it shows your actual total invested, current value, gain/loss, and how a lump-sum-on-day-one would have compared over that same window." },
    ],
  },
  {
    slug: 'peg-ratio-explained',
    title: 'PEG Ratio Explained: The Metric Behind Our Stock Rankings',
    description: "What PEG actually corrects for that P/E alone misses, how to read a PEG number, and its real limitations.",
    date: '2026-09-05',
    readTime: '5 min read',
    relatedPath: '/stocks',
    relatedLabel: 'See PEG-ranked stocks',
    sections: [
      { p: "PEG ratio is P/E ratio divided by expected earnings growth rate: PEG = (Price / Earnings) ÷ (EPS Growth %). It exists to fix a specific blind spot in P/E alone." },
      { h2: "The problem PEG fixes" },
      { p: 'A stock with a P/E of 30 looks expensive next to one with a P/E of 15 — until you notice the first one is growing earnings at 40% a year and the second at 5%. P/E alone can\'t tell you whether a "high" valuation is actually justified by growth. PEG folds growth into the same number, so a high-growth company and a low-growth company become comparable on one scale.' },
      { h2: 'How to read a PEG number' },
      { p: 'A PEG around 1.0 is the traditional rough benchmark for "fairly valued relative to growth" — below 1 has historically been read as potentially undervalued, above 1 as potentially overvalued or already pricing in future growth. This is a heuristic from Peter Lynch\'s writing, not a law — plenty of well-run companies trade above 1 for years because the market is willing to pay up for quality, predictability or a moat, not just raw growth.' },
      { h2: "What PEG doesn't capture" },
      { p: "It relies on a growth estimate — usually forward analyst estimates — which can be wrong, revised, or gamed by a single easy comparison quarter. It also doesn't account for debt load, margins, capital intensity, or cyclicality; a cyclical stock's PEG can look great right at the top of its cycle and terrible right at the bottom, for reasons that have nothing to do with the business getting better or worse." },
      { h2: 'How MetalCalc uses it' },
      { p: "The Stocks page's rankings table sorts by PEG among curated AI/Semiconductor/Tech names, and the Trade Signals section factors it alongside EPS/revenue growth YoY, 52-week range position, and momentum into one composite score — not PEG alone. It's one input in a multi-factor score, same caveat as everywhere else on this site: today's snapshot, not investment advice." },
    ],
  },
  {
    slug: 'position-sizing-101',
    title: 'Position Sizing 101: The Math That Keeps One Bad Trade From Wrecking Your Account',
    description: 'Fixed-fractional position sizing explained — how risking a set % per trade, not a set dollar amount, protects an account over many trades.',
    date: '2026-09-09',
    readTime: '5 min read',
    relatedPath: '/position-size',
    relatedLabel: 'Calculate your own position size',
    sections: [
      { p: "Most blown trading accounts don't die from one bad thesis — they die from betting too much on it. Position sizing is the part of risk management that has nothing to do with being right about a trade." },
      { h2: 'The core idea: risk a % of your account, not a fixed dollar amount' },
      { p: "Fixed-fractional position sizing means you decide upfront to risk a small, consistent percentage of your total account on any single trade — commonly 1-2% — regardless of how confident you feel. Position size is then derived from that percentage, your stop-loss distance, and your account size, not chosen first." },
      { h2: 'The formula' },
      { p: "Position size = (Account size × Risk %) ÷ (Entry price − Stop-loss price). A wider stop-loss automatically means a smaller position size at the same risk percentage — the math keeps risk constant even as your stop distance changes." },
      { h2: 'Why this matters more than being "right"' },
      { p: "A trader risking 1% per trade can be wrong 10 times in a row and still have roughly 90% of their account left to keep trading. A trader risking 20% per trade is functionally out of the game after 4-5 bad trades — even if their long-run win rate is identical. Survival, not any single trade's outcome, is what position sizing protects." },
      { h2: 'A common mistake this catches' },
      { p: "Doubling position size after a loss to \"win it back faster\" does the opposite of what fixed-fractional sizing is designed to do — it increases risk exactly when a string of losses has already reduced the account cushion. Recalculating position size off the current (smaller) account balance, not the size before the losses, is what keeps risk percentage actually constant." },
    ],
  },
  {
    slug: 'rsi-explained-overbought-oversold',
    title: 'RSI Explained: What Overbought and Oversold Actually Mean',
    description: 'How RSI is calculated, why 70/30 are the conventional thresholds, and the specific way it can mislead you in a strong trend.',
    date: '2026-09-10',
    readTime: '5 min read',
    relatedPath: '/crypto',
    relatedLabel: 'See live RSI on any coin\'s timeframe signals',
    sections: [
      { p: "RSI (Relative Strength Index) measures the speed and size of recent price gains versus recent losses, scaled to a 0-100 number. It's one of the most widely used momentum indicators — and one of the most widely misread." },
      { h2: 'How it\'s actually calculated' },
      { p: "Over a lookback period (commonly 14 candles), RSI compares the average size of up-moves to the average size of down-moves. If gains have dominated, RSI trends toward 100. If losses have dominated, it trends toward 0. A reading of 50 means gains and losses have been roughly balanced over the period." },
      { h2: 'Why 70 and 30 are the conventional lines' },
      { p: "Above 70 is conventionally labeled \"overbought,\" below 30 \"oversold\" — meaning the recent move has been unusually one-sided in that window, not that the asset is objectively expensive or cheap. These thresholds are convention, not a law of markets; some traders use 80/20 for more volatile assets specifically because 70/30 triggers too often to be useful." },
      { h2: 'The trap: RSI in a strong trend' },
      { p: "In a strong, sustained uptrend, RSI can sit above 70 for a long stretch while price keeps climbing — treating that as an automatic sell signal has caused a lot of traders to exit a winning trend far too early. RSI describes recent momentum, not a guaranteed reversal point." },
      { h2: 'How it\'s used here' },
      { p: "MetalCalc's Crypto timeframe signals combine RSI with a moving-average crossover and raw momentum into one composite verdict per timeframe (15min through 3 months) — RSI alone never decides the signal, exactly because of the trend trap above." },
    ],
  },
  {
    slug: 'melt-value-vs-retail-price',
    title: 'Melt Value vs Retail Price: Why a Gold Chain Costs More Than Its Weight in Gold',
    description: 'What melt value actually measures, why retail price is always higher, and how to check the markup on a specific piece.',
    date: '2026-09-11',
    readTime: '4 min read',
    relatedPath: '/melt-check',
    relatedLabel: 'Check the markup on a specific piece',
    sections: [
      { p: "Melt value is what a piece of jewelry would be worth if it were melted down to raw metal today — weight × purity × spot price, nothing else. Retail price is what you actually pay, and it's always higher." },
      { h2: 'What accounts for the gap' },
      { p: "Making charges (design labor, wastage during crafting), the retailer's margin, and applicable taxes all sit on top of melt value. None of this is inherently unfair — craftsmanship and retail overhead are real costs — but it means comparing a retail price to melt value tells you the markup, not whether you were scammed." },
      { h2: 'Why the markup varies so much between pieces' },
      { p: "A simple machine-stamped band has a small markup over melt value. An intricate handmade design, a branded piece, or one with gemstones can carry a markup many times the metal's melt value — the craftsmanship, brand and stones are what you're paying that premium for, not gold." },
      { h2: 'When a high markup is a red flag vs expected' },
      { p: 'A high markup on a plain, simple design with no special craftsmanship claimed is worth questioning. The same markup on a detailed, branded, or gem-set piece may be entirely reasonable for the work involved. Context matters more than a single "acceptable %" rule of thumb.' },
      { h2: 'Check any specific piece' },
      { p: "Enter the weight, purity and asking price into the Melt vs Retail Markup Checker to see the exact markup percentage using today's spot price — then decide for yourself whether the craftsmanship justifies it." },
    ],
  },
  {
    slug: 'currency-exchange-margins-explained',
    title: 'How Currency Exchange Margins Quietly Cost You Money',
    description: 'What a "quoted rate" actually hides, how dealer margins work, and how to check the real spread against mid-market.',
    date: '2026-09-12',
    readTime: '4 min read',
    relatedPath: '/rate-check',
    relatedLabel: 'Check a quoted rate against mid-market',
    sections: [
      { p: "When a money changer or bank quotes you an exchange rate, it's rarely the actual mid-market rate you'd see on a live FX feed — there's a margin built in, and it's often not disclosed as a separate line item." },
      { h2: 'How the margin hides inside the "rate" itself' },
      { p: 'Unlike a fee, which shows up as a separate charge, an FX margin is baked directly into the exchange rate you\'re quoted. You\'re never shown "mid-market rate + fee" — you\'re shown one number, and the margin is invisible unless you compare it to the real mid-market rate yourself.' },
      { h2: 'Why the margin varies by channel' },
      { p: "Airport currency counters and hotel exchange desks typically carry the widest margins — high convenience, captive customers, low competitive pressure. Bank transfers and reputable online FX services tend to have tighter margins, closer to true mid-market." },
      { h2: 'How to actually check it' },
      { p: 'Compare the rate you\'re quoted against the live mid-market rate for the same currency pair at the same moment. The percentage difference is the real cost of that transaction — often more than any explicit "fee" the provider advertises.' },
      { h2: 'Use it for gold too' },
      { p: "This matters directly for metals: if you're paying in a foreign currency for gold/silver, a bad FX margin on top of the metal price compounds the total premium you're paying. The Exchange Rate Margin Checker compares any quoted rate against live mid-market to show the hidden spread." },
    ],
  },
  {
    slug: 'reverse-calculating-tax',
    title: 'Reverse-Calculating Tax: Finding the Base Price Hidden in a Tax-Inclusive Total',
    description: 'The formula for backing out base price and tax amount from a final tax-inclusive price, and where people get it wrong.',
    date: '2026-09-13',
    readTime: '3 min read',
    relatedPath: '/tax-reverse',
    relatedLabel: 'Reverse-calculate a tax-inclusive price',
    sections: [
      { p: "You're handed a final price that already includes tax, and you need to know the pre-tax base price and the tax amount separately — common with jewelry bills, invoices, and receipts that don't itemize." },
      { h2: 'The formula (and the common mistake)' },
      { p: "Base price = Final price ÷ (1 + tax rate). The mistake people make is subtracting the tax rate percentage directly from the final price instead of dividing — for a 10% tax rate, that means wrongly subtracting 10% of the final price instead of correctly dividing by 1.10. Those give different, and wrong, answers because the tax rate applies to the base price, not the final price." },
      { h2: 'Worked example' },
      { p: "Final price is $110, tax rate is 10%. Correct: base price = $110 ÷ 1.10 = $100, tax amount = $10. Incorrect: $110 − ($110 × 10%) = $99 — subtly wrong, and the error grows with higher tax rates." },
      { h2: 'Why this comes up so often with jewelry' },
      { p: "Jewelry bills frequently show one final number covering metal value, making charges and tax combined. Reverse-calculating the tax portion is the first step to then separating metal value from making charges — see the Jewelry Bill Breakdown tool for the fuller decomposition." },
    ],
  },
  {
    slug: 'what-diversification-score-measures',
    title: 'What a Diversification Score Actually Measures (and What It Doesn\'t)',
    description: 'The math behind an allocation-based diversification score, what a high or low number means, and its real blind spot.',
    date: '2026-09-14',
    readTime: '4 min read',
    relatedPath: '/net-worth',
    relatedLabel: 'See your own diversification score',
    sections: [
      { p: "A diversification score condenses \"how is my money spread across asset classes\" into one number. Here's what's actually inside it." },
      { h2: 'The math: Herfindahl-Hirschman Index (HHI)' },
      { p: "HHI sums the squared percentage share of each holding. Squaring means concentration is punished harder than the raw percentages suggest — a single asset at 100% scores far worse than the arithmetic gap to an even split would imply, because a 100% share squared is 1.0, dominating the sum. The score here is normalized to 0-100, so 100 means a perfectly even split across categories and 0 means everything in one." },
      { h2: 'What a high score tells you' },
      { p: "Your capital is spread evenly across the categories being measured (metals, stocks, crypto). It does not tell you those categories are uncorrelated, or that any individual position is well-chosen — it's purely about allocation spread." },
      { h2: 'The blind spot: correlation' },
      { p: "This is the important limit. An allocation score treats three asset classes as three independent bets by definition — but if all three move together on the same macro trigger (say, a broad risk-off event hitting stocks, crypto and even gold simultaneously in a liquidity crunch), a high allocation-diversification score doesn't protect you the way it implies. Pair it with an actual correlation check where one's available, like the crypto-only correlation tool on the Crypto page." },
      { h2: 'What to actually do with the number' },
      { p: "Treat it as one input on portfolio construction — flag heavy concentration in one asset class, but don't treat a high score alone as proof you're protected from a broad-based downturn." },
    ],
  },
  {
    slug: 'correlation-vs-diversification',
    title: "Correlation vs Diversification: Why Two Assets Can Both \"Diversify\" You and Still Crash Together",
    description: 'The difference between allocation-based diversification and correlation, and why you need both to actually reduce risk.',
    date: '2026-09-15',
    readTime: '4 min read',
    relatedPath: '/crypto',
    relatedLabel: 'Check correlation across your crypto watchlist',
    sections: [
      { p: "You can be \"diversified\" by allocation and still own assets that move together almost every day. These are two different questions, and mixing them up is a common portfolio mistake." },
      { h2: 'Diversification (allocation) asks: how spread out is my capital?' },
      { p: "50% in one coin and 50% in another is, by allocation, perfectly even — a diversification score would read that as well-spread. It says nothing about whether those two coins actually behave independently." },
      { h2: 'Correlation asks: do these move together?' },
      { p: "A same-direction correlation check looks at the actual daily price history of two assets and measures what percentage of days they moved the same direction (both up or both down). Two coins can be perfectly allocation-diversified and still show 90%+ same-direction movement — meaning a bad day for one is very likely a bad day for the other too." },
      { h2: 'Why this happens so often in crypto specifically' },
      { p: "A large share of crypto assets are driven by the same macro risk-on/risk-off sentiment and overall market liquidity — Bitcoin's mood pulls a lot of altcoins with it regardless of each project's individual fundamentals. This is exactly why crypto portfolios that look diversified by coin count often aren't diversified by actual behavior." },
      { h2: 'Use both checks together' },
      { p: "An allocation score (Net Worth) tells you if your capital is spread out. A correlation check (Crypto watchlist tab) tells you if that spread actually behaves independently. High correlation with a high diversification score is the specific combination worth noticing — it means the spread is more cosmetic than protective." },
    ],
  },
  {
    slug: 'storage-and-insurance-hidden-cost',
    title: 'Storage and Insurance: The Hidden Carrying Cost of Holding Physical Metal',
    description: 'Why physical gold/silver isn\'t "free" to hold, what storage and insurance actually cost over time, and the break-even math.',
    date: '2026-09-16',
    readTime: '4 min read',
    relatedPath: '/storage-cost',
    relatedLabel: 'Estimate your own carrying cost',
    sections: [
      { p: "Physical gold doesn't pay a dividend, doesn't accrue interest, and — unlike the number in a brokerage app — actually costs something to keep secure over time. That carrying cost is easy to forget when you're only looking at the spot price chart." },
      { h2: 'What storage actually costs' },
      { p: "A home safe is a one-time cost but has real limits on security and insurability. A bank safe deposit box or a specialized precious-metals depository charges an ongoing fee — annual or monthly — that scales with either a flat rate or the value stored." },
      { h2: 'Insurance is a separate, recurring cost' },
      { p: "Home insurance policies often cap jewelry/precious-metals coverage far below what a serious holding is worth, meaning a real holding needs a supplemental policy — priced as a percentage of insured value per year, recurring for as long as you hold the metal." },
      { h2: 'The break-even question this creates' },
      { p: 'If storage + insurance cost a combined 1% of holding value per year, your gold needs to appreciate more than 1% annually just to keep pace with the carrying cost, before you\'re ahead in real terms. This doesn\'t make physical gold a bad idea — it means the "gold has no holding cost" assumption is wrong, and the real comparison is against how much appreciation you actually expect.' },
      { h2: 'Run the actual numbers' },
      { p: 'The Storage & Insurance Cost Calculator projects this carrying cost over a chosen time horizon and shows the price appreciation needed just to break even — turning a vague sense of "gold is free to hold" into an actual number.' },
    ],
  },
  {
    slug: 'alloy-mixing-math-explained',
    title: 'Alloy Mixing Math: What Happens When You Melt Two Different Purities Together',
    description: 'The weighted-average formula behind melting two gold/silver purities together, with a worked example.',
    date: '2026-09-17',
    readTime: '3 min read',
    relatedPath: '/alloy-mix',
    relatedLabel: 'Calculate your own blended purity',
    sections: [
      { p: "Melting a 22k piece and a 14k piece together doesn't give you 18k — the result depends on the weight of each piece, not just the average of their karats." },
      { h2: 'The actual formula' },
      { p: "Blended purity = (weight₁ × purity₁ + weight₂ × purity₂) ÷ (weight₁ + weight₂). It's a weight-weighted average, so a small amount of low-purity metal barely moves the result if melted with a much larger amount of high-purity metal, and vice versa." },
      { h2: 'Worked example' },
      { p: "Melt 10g of 22k (0.9167 purity) with 5g of 14k (0.5833 purity): blended purity = (10 × 0.9167 + 5 × 0.5833) ÷ 15 = (9.167 + 2.9165) ÷ 15 ≈ 0.806 — roughly 19.3k equivalent, closer to the 22k piece because it's twice the weight." },
      { h2: "Why equal-weight melts don't give a simple average of the karats" },
      { p: "Even with equal weights, the average of the karat numbers (22 and 14 → 18) happens to roughly match the purity-fraction average here, but that's coincidental to how karat scales linearly to 24 — the underlying math is always on purity fractions and weight, not on karat numbers directly, and gets more error-prone the more pieces and purities you mix." },
      { h2: 'Skip the manual math' },
      { p: "The Alloy Mixing Calculator takes any number of pieces at their own weight and purity and computes the exact blended result — useful before melting down mixed-karat scrap or old jewelry." },
    ],
  },
  {
    slug: '52-week-range-demand-supply-proxy',
    title: "The 52-Week Range as a Demand/Supply Proxy: What It Can and Can't Tell You",
    description: 'Why position within the 52-week range is used as a stand-in for real support/resistance, and where that substitution breaks down.',
    date: '2026-09-18',
    readTime: '4 min read',
    relatedPath: '/stocks',
    relatedLabel: "See 52-week range position on ranked stocks",
    sections: [
      { p: "Real support/resistance analysis needs intraday price-action history — every touch, every rejection, every volume spike at a level. When that data isn't available, position within the 52-week high/low range is a common stand-in. It's a proxy, not the real thing, and the difference matters." },
      { h2: 'What it actually measures' },
      { p: "Range position = (current price − 52-week low) ÷ (52-week high − 52-week low), as a percentage. Near 0% means trading close to the yearly low; near 100% means close to the yearly high. That's the entire calculation — no volume, no number of times a level was tested, no order-flow data." },
      { h2: 'Why it\'s used as a demand/supply proxy at all' },
      { p: 'The logic: a price near its yearly low has, on average, faced less recent buying pressure, and a price near its yearly high has faced less recent selling pressure — a rough, indirect signal about where demand and supply might sit, built entirely from two data points (the high and the low) rather than the full price history in between.' },
      { h2: 'Where the substitution breaks down' },
      { p: 'A stock can sit at 15% of its range not because it is near support, but because it is in a genuine structural decline with no support nearby at all. A real support level needs to show it actually held on prior tests — the 52-week range alone cannot distinguish "cheap relative to its own year" from "falling for a reason."' },
      { h2: 'How to use it responsibly' },
      { p: "Treat range position as one input describing where today sits relative to the past year, not a prediction of where price bounces next. MetalCalc's stock rankings show it as one factor among several (PEG, growth, momentum) in a composite score — never the sole basis for a signal." },
    ],
  },
]

export function getPostBySlug(slug) {
  return POSTS.find((p) => p.slug === slug) ?? null
}
