// SEO/guide landing pages — static content, rendered by the single generic
// LandingPage.jsx at /:landingSlug. Add a page by appending here; also add a
// sitemap entry and update public/llms.txt — nothing else needs wiring.
// (Live-price pages like Gold Rate Today have their own dedicated component
// instead, since they need useMarket() — this array is for static content only.)
export const LANDING_PAGES = [
  {
    slug: 'gold-price-per-gram',
    title: 'Gold Price Per Gram: How It\'s Calculated',
    description: 'How spot gold (quoted per troy ounce) converts to a price per gram, and how karat purity changes the number.',
    h1: 'Gold price per gram: how it\'s calculated',
    intro: 'Spot gold is quoted per troy ounce internationally, but almost everyone actually thinks in grams. Here\'s the exact conversion.',
    sections: [
      { h2: 'The conversion' },
      { p: '1 troy ounce = 31.1034768 grams. So price per gram (24k) = spot price per ounce ÷ 31.1034768. If spot is $2,000/oz, that\'s roughly $64.30/gram for 24k (.999 fine) gold.' },
      { h2: 'Adjusting for karat' },
      { p: 'Lower karats contain less actual gold by weight, so multiply by the purity fraction: 22k = ×0.9167, 18k = ×0.75, 14k = ×0.5833, 10k = ×0.4167. An 18k chain isn\'t worth 75% of a 24k chain\'s weight in currency terms by coincidence — that\'s literally the gold content ratio.' },
      { h2: 'Why your jeweler\'s number is different' },
      { p: 'The per-gram spot value above is the raw metal value only. Retail jewelry prices add making charges, wastage, and taxes on top — often a meaningful percentage of the final bill. See the Jewelry Bill Breakdown tool to isolate exactly how much of a quoted price is metal vs markup.' },
    ],
    relatedLinks: [
      { path: '/gold-rate-today', label: 'See today\'s live gold rate per gram' },
      { path: '/convert', label: 'Convert between karat, fineness and percent' },
      { path: '/bill-breakdown', label: 'Break down a jewelry bill into metal + markup' },
    ],
    updated: '2026-09-18',
    category: 'Metals',
    keywords: ['gold price per gram', 'gold price per gram today', 'gold price per gram in india', 'gold price per gram 22k'],
    faqs: [
      { q: 'What is the gold price per gram today?', a: 'It changes with live spot prices — MetalCalc\'s Gold Rate Today page shows it live, already converted from the per-ounce spot quote.' },
      { q: 'How do I convert gold price per ounce to per gram?', a: 'Divide the price per troy ounce by 31.1034768 — that\'s the exact number of grams in a troy ounce.' },
      { q: 'Why is gold price per gram different for 22k vs 24k?', a: 'Because 22k contains less pure gold by weight (91.67% vs 99.9%) — multiply the 24k per-gram price by the karat\'s purity fraction to get its value.' },
      { q: 'Is gold price per gram the same everywhere in the world?', a: 'The underlying international spot price is the same, but local prices can differ slightly due to currency conversion, import duties, and local market premiums.' },
      { q: 'Does gold price per gram include making charges?', a: 'No — spot price per gram is the raw metal value only. A jeweler\'s quoted price adds making charges and taxes on top.' },
    ],
  },
  {
    slug: '24k-vs-22k-gold-difference',
    title: '24k vs 22k Gold: What\'s the Actual Difference?',
    description: 'The real difference between 24k and 22k gold — purity, durability, color, and value — with the exact math.',
    h1: '24k vs 22k gold: what\'s the actual difference?',
    intro: 'The number after "k" isn\'t a grading scale — it\'s a fraction. Here\'s exactly what changes between 24k and 22k.',
    sections: [
      { h2: 'Purity, in exact numbers' },
      { p: '24k is 99.9% pure gold (.999 fineness). 22k is 22/24 = 91.67% pure gold, with the remaining ~8.3% being other metals (usually copper and/or silver) added as an alloy.' },
      { h2: 'Why alloy is added at all' },
      { p: 'Pure gold is soft — 24k jewelry scratches and deforms more easily than alloyed gold. 22k (and lower karats) trade some purity for hardness and durability, which is why most everyday jewelry isn\'t 24k despite 24k being "purer."' },
      { h2: 'The value difference' },
      { p: 'At the same weight, 22k is worth 91.67% of what 24k is worth in metal value — because that\'s the actual gold content ratio, not a marketing distinction. A 10-gram 22k chain contains the same gold as a 9.167-gram 24k piece.' },
      { h2: 'Color difference' },
      { p: '24k has gold\'s natural deep yellow color. 22k, with a small amount of alloy, looks nearly identical but can shift very slightly depending on which alloy metal was used — copper alloys warm the tone, silver alloys cool it.' },
    ],
    relatedLinks: [
      { path: '/convert', label: 'Convert 24k value to 22k, 18k, 14k or 10k' },
      { path: '/alloy-mix', label: 'See what happens when purities are melted together' },
    ],
    updated: '2026-09-18',
    category: 'Metals',
    keywords: ['22k vs 24k gold', '22k vs 24k gold difference', '22k vs 24k gold which is best', '22k vs 24k gold resale value'],
    faqs: [
      { q: 'Which is better, 22k or 24k gold?', a: "Neither is universally 'better' — 24k is purer but softer, 22k trades some purity for durability, which is why most everyday jewelry is 22k or lower." },
      { q: 'What is the price difference between 22k and 24k gold?', a: '22k is worth 91.67% of 24k\'s value at the same weight — that\'s the exact gold-content ratio, not a marketing margin.' },
      { q: 'Does 22k gold look different from 24k?', a: 'Nearly identical in color, with a very slight tone shift depending on the alloy metal used — copper warms the tone, silver cools it.' },
      { q: 'Which has better resale value, 22k or 24k gold?', a: '24k generally resells closer to its full metal value since it\'s already near-pure; 22k resells at its proportional gold content, plus whatever making charges were already paid are typically not recovered either way.' },
      { q: 'Why is 24k gold not used for everyday jewelry?', a: 'Pure gold is soft and scratches/deforms easily — alloying with copper or silver (making it 22k or lower) adds hardness and durability for daily wear.' },
    ],
  },
  {
    slug: 'best-time-to-buy-gold',
    title: 'Is There a "Best Time" to Buy Gold?',
    description: 'Why timing gold purchases is harder than it sounds, and two practical frameworks that don\'t rely on predicting price direction.',
    h1: 'Is there a "best time" to buy gold?',
    intro: 'Short answer: nobody reliably calls the bottom. Here\'s a more useful way to think about it.',
    sections: [
      { h2: 'Why timing is genuinely hard' },
      { p: 'Gold\'s price reacts to macro variables (real interest rates, currency strength, geopolitical risk, central bank buying) that are themselves unpredictable. Anyone claiming a reliable "best time to buy" signal is overstating their edge — including seasonal patterns, which are weak and inconsistent across years.' },
      { h2: 'Framework 1: dollar-cost averaging' },
      { p: 'Instead of trying to pick a bottom, buy a fixed amount on a fixed schedule regardless of price. This removes the timing decision entirely and smooths your average cost — see the fuller breakdown in the Dollar-Cost Averaging Into Crypto post (the same math applies to metals).' },
      { h2: 'Framework 2: goal-based buying' },
      { p: 'Rather than asking "is now a good time," ask "how much do I need to buy monthly to hit a target weight by a target date." The Savings Goal Projector answers that directly using live prices, sidestepping the timing question altogether.' },
      { h2: 'The one thing that does matter: valuation context' },
      { p: 'The gold-silver ratio and how far gold is from a recent range can give context on whether you\'re paying near a relative high or low — not a signal to act on alone, but useful context alongside a plan.' },
    ],
    relatedLinks: [
      { path: '/savings-goal', label: 'Plan monthly buys toward a weight goal' },
      { path: '/blog/dollar-cost-averaging-crypto-does-it-work', label: 'Read: does DCA actually work?' },
      { path: '/gold-vs-silver-investment', label: 'Check the live gold-silver ratio' },
    ],
    updated: '2026-09-18',
    category: 'Metals',
    keywords: ['best time to buy gold', 'when to buy gold', 'gold investment timing'],
    faqs: [
      { q: 'Is there a best month to buy gold?', a: 'Seasonal patterns are weak and inconsistent year to year — not reliable enough to plan a purchase around.' },
      { q: 'How do I decide when to buy gold without timing the market?', a: 'Two practical options: dollar-cost average a fixed amount on a schedule, or set a weight goal and a monthly plan to reach it — both skip the timing decision entirely.' },
      { q: 'Does the gold-silver ratio tell me when to buy?', a: "It gives relative-pricing context, not a buy signal on its own — useful alongside a plan, not a replacement for one." },
      { q: 'Should I wait for a dip to buy gold?', a: 'Waiting for a dip that may not come is a common reason people never actually buy — a scheduled plan avoids that specific trap.' },
      { q: 'Is gold a good long-term investment regardless of timing?', a: 'That depends on your own goals and risk tolerance — this page is about removing the timing question, not making an investment recommendation.' },
    ],
  },
  {
    slug: 'gold-investment-for-beginners',
    title: 'Gold Investment for Beginners: A Practical Starting Guide',
    description: 'The practical basics of investing in physical gold — forms, purity, storage, and how to actually track what you own.',
    h1: 'Gold investment for beginners',
    intro: 'No hype, just the practical basics of buying and holding physical gold.',
    sections: [
      { h2: 'What form to buy' },
      { p: 'Coins and small bars from recognized mints are the most liquid physical forms — easiest to verify and resell. Jewelry carries making charges you don\'t get back on resale, so it\'s a poor vehicle for pure investment even though it\'s a common way people end up holding gold anyway.' },
      { h2: 'Purity matters for investment-grade gold' },
      { p: 'Investment coins/bars are typically .999 or .9999 fine (24k-equivalent). Lower-karat jewelry gold is fine to own, but its resale value is discounted for both the lower gold content and the making charges you already paid.' },
      { h2: 'Storage and insurance are real costs' },
      { p: 'Physical gold needs to be stored somewhere secure, and larger holdings are worth insuring — both cost money over time. Run the numbers with the Storage & Insurance Cost Calculator before assuming physical gold is "free" to hold.' },
      { h2: 'Track it like a portfolio, not a drawer' },
      { p: 'Log weight, purity, and what you paid so you can see real gain/loss, not just a vague sense of "gold went up." My Holdings does this with live pricing and a diversification score if you also hold silver/platinum.' },
    ],
    relatedLinks: [
      { path: '/holdings', label: 'Track your holdings with live value' },
      { path: '/storage-cost', label: 'Estimate storage & insurance cost' },
      { path: '/how-to-calculate-gold-purity', label: 'How to calculate gold purity' },
    ],
    updated: '2026-09-18',
    category: 'Metals',
    keywords: ['gold investment for beginners', 'how to invest in gold', 'buying gold for the first time'],
    faqs: [
      { q: 'What form of gold is best for a beginner investor?', a: 'Coins and small bars from recognized mints are the most liquid and easiest to verify/resell — jewelry carries making charges you don\'t recover on resale.' },
      { q: 'What purity should investment gold be?', a: 'Typically .999 or .9999 fine (24k-equivalent) for coins/bars — lower-karat jewelry gold is fine to own but resells at a discount for both lower content and unrecovered making charges.' },
      { q: 'Does gold cost money to hold?', a: 'Yes — storage and insurance are real ongoing costs for a serious physical holding, unlike a number in a brokerage app.' },
      { q: 'How do I track my gold investment over time?', a: "Log the weight, purity and price paid per item so you can see real gain/loss — a vague sense of 'gold went up' isn't the same as knowing your actual return." },
      { q: 'How much gold should a beginner buy?', a: 'That depends on your own goals and risk tolerance — this guide covers the practical mechanics of buying/holding, not a specific allocation recommendation.' },
    ],
  },
  {
    slug: 'silver-investment-guide',
    title: 'Silver Investment Guide: What Makes It Different From Gold',
    description: 'What actually makes silver a different investment than gold — industrial demand, volatility, storage bulk, and liquidity.',
    h1: 'Silver investment guide',
    intro: 'Silver isn\'t "cheap gold" — it behaves differently for structural reasons worth understanding before you buy.',
    sections: [
      { h2: 'Industrial demand is the key difference' },
      { p: 'A meaningful share of silver demand comes from electronics, solar panels and other industrial uses — not just investment/jewelry demand like gold. That extra demand driver is a large part of why silver is more volatile than gold in both directions.' },
      { h2: 'Storage takes more room' },
      { p: 'Silver is far less valuable per gram than gold, so the same dollar amount of silver takes up dramatically more physical space and weight — a real practical consideration if you\'re storing it yourself.' },
      { h2: 'Liquidity and spreads' },
      { p: 'Gold generally has tighter buy/sell spreads and wider acceptance for resale. Silver dealer spreads can be wider, particularly for smaller or less-recognized bar/coin formats.' },
      { h2: 'How to think about an allocation' },
      { p: 'The gold-silver ratio gives context on relative pricing, but position size should also weigh your volatility tolerance and how easily you\'d need to liquidate. Track both together and see a real diversification score across your metals on My Holdings.' },
    ],
    relatedLinks: [
      { path: '/gold-vs-silver-investment', label: 'Compare gold vs silver directly' },
      { path: '/holdings', label: 'Track a mixed metals portfolio' },
      { path: '/blog/gold-silver-ratio-explained', label: 'Read: the gold-silver ratio explained' },
    ],
    updated: '2026-09-18',
    category: 'Metals',
    keywords: ['how to invest in silver', 'silver investment guide', 'silver vs gold investment'],
    faqs: [
      { q: 'Why is silver more volatile than gold?', a: 'Silver has real industrial demand (electronics, solar) on top of investment demand, which is an extra demand driver gold mostly lacks — that extra driver adds volatility in both directions.' },
      { q: 'Is silver harder to store than gold?', a: "Yes in practical terms — silver is worth far less per gram than gold, so the same dollar amount takes up much more physical space and weight." },
      { q: 'Is silver less liquid than gold?', a: 'Generally yes — gold has tighter buy/sell spreads and wider resale acceptance; silver dealer spreads can be wider, especially for smaller or less-recognized formats.' },
      { q: 'How much silver should I hold vs gold?', a: 'The gold-silver ratio gives pricing context, but your own volatility tolerance and liquidity needs matter just as much — there\'s no single correct split.' },
      { q: 'Can I track silver alongside gold in one place?', a: 'Yes — MetalCalc\'s Holdings page tracks both together with live value and a diversification score across your metals.' },
    ],
  },
  {
    slug: 'crypto-portfolio-diversification-guide',
    title: 'Crypto Portfolio Diversification: What Actually Reduces Risk',
    description: 'Why holding many coins doesn\'t automatically mean you\'re diversified, and how to actually check.',
    h1: 'Crypto portfolio diversification: what actually reduces risk',
    intro: 'Holding 10 coins instead of 1 feels diversified. It often isn\'t.',
    sections: [
      { h2: 'The allocation-concentration problem' },
      { p: 'A diversification score based on allocation (like an HHI-style measure) tells you whether your capital is spread evenly or concentrated in one position — useful, but it only looks at position sizing, not whether those positions actually move independently of each other.' },
      { h2: 'The correlation problem allocation scores miss' },
      { p: "Most large-cap crypto assets move together on macro risk-on/risk-off days — sometimes 70%+ of days in the same direction. Ten altcoins that all track Bitcoin's mood aren't ten independent bets; they're one leveraged bet on the same thing. This is exactly why a correlation check matters alongside an allocation score." },
      { h2: 'What a real diversification check looks like' },
      { p: 'Two numbers together: an allocation-based diversification score (across metals/stocks/crypto on Net Worth), and a same-direction correlation % across your specific coins (on the Crypto page\'s watchlist tab). High correlation between your "diversified" coins is a flag worth acting on, not a footnote.' },
    ],
    relatedLinks: [
      { path: '/net-worth', label: 'See your cross-asset diversification score' },
      { path: '/crypto', label: 'Check correlation across your watchlist' },
    ],
    updated: '2026-09-18',
    category: 'Markets',
    keywords: ['crypto portfolio tracker', 'crypto portfolio diversification', 'crypto diversification app'],
    faqs: [
      { q: 'Does holding more coins mean I am more diversified?', a: 'Not necessarily — an allocation score can look spread-out while the coins themselves move together most days, which is not real diversification.' },
      { q: 'How correlated are most crypto assets?', a: 'Often highly — many altcoins track Bitcoin\'s overall mood on risk-on/risk-off days, sometimes moving the same direction 70%+ of days.' },
      { q: 'What two numbers should I check for real crypto diversification?', a: 'An allocation-based diversification score (how spread your capital is) and a same-direction correlation percentage across your specific coins (whether they actually move independently).' },
      { q: 'Can I check correlation between my crypto holdings for free?', a: "Yes — MetalCalc's Crypto page includes a same-direction correlation check across your watchlist, no account needed." },
      { q: 'Is a high correlation between my coins always a problem?', a: 'Not necessarily a problem, but it is a flag worth knowing about — it means those coins are not protecting you from each other in a downturn, which matters if that was the goal.' },
    ],
  },
  {
    slug: 'understanding-stock-trade-signals',
    title: 'Understanding Automated Stock Trade Signals (What They Can\'t Tell You)',
    description: 'How rule-based buy/sell signals are actually built, what factors go in, and their honest limitations.',
    h1: 'Understanding automated stock trade signals',
    intro: 'A "Buy" or "Sell" label feels authoritative. Here\'s what\'s actually behind one.',
    sections: [
      { h2: 'It\'s a weighted scorecard, not a prediction' },
      { p: 'A rule-based signal combines several factors into one score — for example PEG ratio, EPS/revenue growth, position in the 52-week range, and recent momentum — and converts the combined score into Buy/Sell/Hold. No single factor decides it, and no factor claims to predict the future; each one describes a fact about today.' },
      { h2: 'Why 52-week range position is used as a proxy' },
      { p: 'Where a stock sits in its 52-week range (near the low vs near the high) is a rough demand/supply proxy when real order-flow/price-action data isn\'t available. It\'s not the same as a technical support/resistance level built from actual price action — treat it as a coarse signal, not precision.' },
      { h2: 'What these signals structurally can\'t see' },
      { p: 'They don\'t know about news that hasn\'t happened yet, don\'t price in company-specific risk beyond what\'s in the growth/valuation numbers, and can flip quickly if the underlying data changes. A composite score is a starting point for research, not a substitute for it.' },
      { h2: 'Where to see one in practice' },
      { p: 'MetalCalc\'s Stocks page combines these factors transparently and shows the reasoning behind each Buy/Sell call — read the "reason" text, not just the label.' },
    ],
    relatedLinks: [
      { path: '/stocks', label: 'See live trade signals with reasoning' },
      { path: '/blog/peg-ratio-explained', label: 'Read: PEG ratio explained' },
    ],
    updated: '2026-09-18',
    category: 'Markets',
    keywords: ['stock trade signal', 'automated buy sell signal', 'stock screener signal'],
    faqs: [
      { q: 'How do automated stock trade signals actually work?', a: 'They combine several factors — like PEG ratio, growth rates, and 52-week range position — into one weighted score, then convert that score into a Buy/Sell/Hold label.' },
      { q: 'Can I trust an automated Buy/Sell signal?', a: "Treat it as a starting point for research, not a substitute for it — it can't see news that hasn't happened yet and can flip quickly if the underlying data changes." },
      { q: 'What is the 52-week range position in a trade signal?', a: "A rough proxy for demand/supply — where a stock sits between its yearly low and high — used when real price-action data isn't available." },
      { q: 'Why does MetalCalc show a reason with each trade signal?', a: "So the label isn't a black box — you can see exactly which factors (PEG, growth, momentum) drove the Buy/Sell/Hold call." },
      { q: 'Are stock trade signals the same as financial advice?', a: 'No — they are a transparent, rule-based scorecard from public data, not personalized financial advice.' },
    ],
  },
  {
    slug: 'savings-goal-vs-lump-sum-gold',
    title: 'Savings Goal vs Lump Sum: Two Ways to Build a Gold Position',
    description: 'The tradeoffs between saving toward a gold weight goal monthly versus buying a lump sum today.',
    h1: 'Savings goal vs lump sum: two ways to build a gold position',
    intro: 'Both get you to a target weight of gold. They get there very differently.',
    sections: [
      { h2: 'The lump-sum path' },
      { p: 'Buy the full target weight today at today\'s price. Simple, and if gold rises afterward, you\'re fully exposed to the gain from day one. The tradeoff: you\'re also fully exposed if it falls right after you buy, and it requires having the full amount available now.' },
      { h2: 'The savings-goal path' },
      { p: 'Set a target weight and a monthly contribution, and buy smaller amounts over time until you reach it. This spreads your entry price across many points instead of one, and doesn\'t require the full capital upfront — useful if you\'re building toward the goal from income rather than a windfall.' },
      { h2: 'Which one actually fits your situation' },
      { p: 'If you already have the capital and don\'t need it for anything else, a lump sum is simpler and has no "waiting" cost. If you\'re accumulating from ongoing income, a savings-goal plan is the realistic option regardless of which one is mathematically "better" in hindsight.' },
      { h2: 'Plan either one with live numbers' },
      { p: 'The Savings Goal Projector shows exactly how long a fixed monthly amount takes to reach a weight target at current prices — useful for planning even if you end up buying some of it in a lump sum later.' },
    ],
    relatedLinks: [
      { path: '/savings-goal', label: 'Project your own savings goal timeline' },
      { path: '/blog/dollar-cost-averaging-crypto-does-it-work', label: 'Read: does DCA actually work?' },
    ],
    updated: '2026-09-18',
    category: 'Metals',
    keywords: ['savings goal calculator', 'savings goal calculator monthly', 'gold savings plan'],
    faqs: [
      { q: 'Is it better to buy gold as a lump sum or save monthly toward it?', a: 'Lump sum is simpler and fully exposed to gains/losses from day one; a monthly savings plan spreads entries over time and doesn\'t need the full capital upfront — the right one depends on whether you have the capital now or are building from income.' },
      { q: 'How do I plan monthly savings toward a gold weight goal?', a: "Set a target weight and date, then MetalCalc's Savings Goal Projector calculates the monthly amount needed at current prices." },
      { q: 'Does a savings goal plan guarantee I reach my target weight?', a: 'It projects the required contribution at today\'s prices — if prices rise, the same monthly amount buys less weight than projected, and vice versa if prices fall.' },
      { q: 'Can I switch from a savings plan to a lump sum later?', a: 'Yes — planning with a savings goal doesn\'t lock you in; it\'s a useful reference point even if you end up buying some of it in a lump sum later.' },
      { q: 'Does this work for silver too?', a: 'Yes — the Savings Goal Projector works for any supported metal, not just gold.' },
    ],
  },
  {
    slug: 'jewelry-making-charges-explained',
    title: 'Jewelry Making Charges Explained: What You\'re Actually Paying For',
    description: 'What making charges cover, typical structures (flat vs percentage), and how to check if a quoted price is fair.',
    h1: 'Jewelry making charges explained',
    intro: 'The gap between a piece\'s metal value and its price tag has a name — here\'s what it actually covers.',
    sections: [
      { h2: 'What making charges pay for' },
      { p: 'Labor, design complexity, wastage during crafting, and the retailer\'s margin. Intricate handmade designs command higher making charges than simple machine-made pieces, since more skilled labor and material loss goes into them.' },
      { h2: 'Flat fee vs percentage-based charges' },
      { p: 'Some jewelers charge a flat amount per gram regardless of design; others charge a percentage of the metal value (often higher for elaborate designs). A percentage-based charge on an expensive metal day costs more in absolute terms for the identical design — worth knowing before you compare two quotes given on different days.' },
      { h2: 'How to check if a quote is reasonable' },
      { p: 'Back out the pure metal value at the day\'s spot price and purity, then see what percentage the making charge + tax represents of the total bill. There\'s no universal "fair" percentage — it varies hugely by design complexity and market — but seeing the actual number lets you compare across jewelers and negotiate from information instead of guessing.' },
    ],
    relatedLinks: [
      { path: '/bill-breakdown', label: 'Break down a jewelry bill into metal + markup' },
      { path: '/melt-check', label: 'Check markup over pure melt value' },
    ],
    updated: '2026-09-18',
    category: 'Tools',
    keywords: ['jewelry making charges', 'jewellery making charges per gram', 'jewellery making charges gst rate'],
    faqs: [
      { q: 'What are jewelry making charges?', a: "The labor, design complexity and wastage cost added on top of a piece's pure metal value — plus the retailer's margin." },
      { q: 'Are jewelry making charges a flat fee or a percentage?', a: 'Both structures exist — some jewelers charge a flat amount per gram, others a percentage of the metal value; a percentage-based charge costs more in absolute terms on an expensive-metal day.' },
      { q: 'How much are typical making charges in India?', a: 'It varies widely by jeweler, design complexity and city — there is no single standard percentage, which is exactly why checking the actual breakdown matters.' },
      { q: 'How do I check if my jewelry making charge is fair?', a: "Back out the pure metal value at today's spot price and purity, then see what percentage the making charge + tax represents of the total bill — compare that number across jewelers." },
      { q: 'Do making charges apply to GST too?', a: 'Making charges are typically taxed, often at a different GST rate than the metal value itself — check your specific bill\'s breakdown rather than assuming one combined rate.' },
    ],
  },
  {
    slug: 'net-worth-tracking-guide',
    title: 'Tracking Net Worth Across Metals, Stocks and Crypto in One Place',
    description: 'Why fragmented net worth tracking hides your real risk, and how to see a combined number without a brokerage aggregator.',
    h1: 'Tracking net worth across metals, stocks and crypto',
    intro: 'Most people\'s wealth is scattered across a jewelry box, a brokerage app, and a crypto exchange — each showing a number in isolation.',
    sections: [
      { h2: 'Why a single combined number matters' },
      { p: 'Seeing "my stocks are up 8%" and "my crypto is down 15%" separately hides the fact that your total net worth might be flat, or that one asset class dominates your risk far more than you think. A combined figure is the only honest picture.' },
      { h2: 'What to include beyond the account balances' },
      { p: 'Unrealized gains on open positions and realized gains from things you\'ve already sold both count toward your actual financial position — tracking only current holdings and ignoring past realized gains/losses understates the full picture.' },
      { h2: 'The diversification check that matters most' },
      { p: 'Once you see a combined total, the next question is whether it\'s actually spread across asset classes or concentrated in one. A diversification score based on how evenly value is spread (not just "I own 3 things") answers that directly.' },
      { h2: 'Keeping it all without a brokerage aggregator' },
      { p: 'This works entirely from manually-entered holdings and portfolios — no bank-level account linking required. Back it up regularly since it\'s stored only in your browser.' },
    ],
    relatedLinks: [
      { path: '/net-worth', label: 'See your combined net worth + P&L' },
      { path: '/backup', label: 'Back up your data' },
    ],
    updated: '2026-09-18',
    category: 'Markets',
    keywords: ['net worth tracker', 'net worth tracker app', 'net worth tracker spreadsheet'],
    faqs: [
      { q: 'Why track net worth across metals, stocks and crypto together?', a: 'Seeing each asset class separately hides whether your total is actually flat and whether one asset class dominates your risk more than you realize — a combined number is the honest picture.' },
      { q: 'Do I need a spreadsheet to track net worth?', a: "No — MetalCalc tracks it from your manually-entered Holdings, Stock and Crypto portfolios automatically, no spreadsheet or bank-level account linking required." },
      { q: 'Does net worth tracking include realized gains from things I already sold?', a: "Yes — both unrealized gains on open positions and realized gains from past sales count toward your actual financial position." },
      { q: 'Is my net worth data stored on a server?', a: 'No — everything is stored only in your browser; back it up regularly using the Backup & Restore tool.' },
      { q: 'Can I see a diversification score alongside my net worth?', a: 'Yes — the Net Worth page shows a diversification score alongside the combined total, based on how evenly value is spread across asset classes.' },
    ],
  },
]

export function getLandingPageBySlug(slug) {
  return LANDING_PAGES.find((p) => p.slug === slug) ?? null
}
