// SEO/guide landing pages — static content, rendered by the single generic
// LandingPage.jsx at /:landingSlug. Add a page by appending here; also add a
// sitemap entry and update public/llms.txt — nothing else needs wiring.
// (Live-price pages like Gold Rate Today have their own dedicated component
// instead, since they need useMarket() — this array is for static content only.)
export const LANDING_PAGES = [
  {
    slug: 'gold-price-per-gram',
    title: 'Gold Price Per Gram: How It\'s Calculated',
    description: 'How spot gold (quoted per troy ounce) converts to a price per gram, and how karat purity changes the number.',
    h1: 'Gold price per gram: how it\'s calculated',
    intro: 'Spot gold is quoted per troy ounce internationally, but almost everyone actually thinks in grams. Here\'s the exact conversion.',
    sections: [
      { p: "Gold is traded internationally in troy ounces, which is a somewhat unusual unit if you don't come from a trading or jewelry background — but almost nobody actually thinks about their own gold in troy ounces day to day. Most people think in grams, whether they're buying a chain, checking what a family piece might be worth, or comparing a quote from a jeweler. This guide walks through the exact math to get from the international troy-ounce spot price to a number in grams that actually means something to you." },
      { h2: 'The core conversion, step by step' },
      { p: "Here's the one fact you need to memorize: 1 troy ounce equals 31.1034768 grams exactly. That's a fixed, unchanging conversion factor — it never varies, unlike the price of gold itself. So the formula for price per gram of pure (24-karat) gold is: spot price per ounce ÷ 31.1034768. As a concrete example, if gold is trading at $2,000 per troy ounce, then $2,000 ÷ 31.1034768 works out to roughly $64.30 per gram for 24k (.999 fine) gold." },
      { h2: 'Why the number changes again once you factor in karat' },
      { p: "The per-gram number above is only for pure, 24-karat gold. Lower karats contain less actual gold by weight — the rest is other metals mixed in as an alloy — so you need to multiply that pure-gold per-gram price by the karat's specific purity fraction to get its real value. The fractions are: 22k = ×0.9167, 18k = ×0.75, 14k = ×0.5833, and 10k = ×0.4167. Here's a detail worth understanding rather than just memorizing: an 18k chain isn't worth exactly 75% of what an identical-weight 24k chain is worth by some marketing convention — that 75% figure is literally the actual gold content ratio in that alloy. It's a measurement, not a pricing decision." },
      { h2: "Why your jeweler's quoted price is a completely different number" },
      { p: "The per-gram spot value calculated above is the raw metal value only — nothing else factored in. A jeweler's actual retail price adds making charges (the cost of actually crafting the piece), some allowance for wastage during that crafting process, and applicable taxes on top of that raw metal value — and together, these can represent a meaningful percentage of what you ultimately pay at the counter. None of that is automatically unfair, but it does mean the number you calculate here is a starting point for comparison, not the final price you should expect to pay." },
      { h2: 'A few situations where this math is genuinely useful' },
      { p: "You're comparing a jeweler's quoted price against the actual gold content to understand how much of it is metal versus markup. You're selling an old piece and want a realistic sense of its floor value before anyone makes you an offer. You've inherited gold in an unfamiliar karat and want to understand what it's actually worth per gram today. You're budgeting for a purchase and want to estimate roughly how much a specific weight will cost before you visit a store. In each case, knowing the real per-gram value for the specific karat you're dealing with gives you a solid number to reason from." },
      { h2: 'Skip the manual math' },
      { p: "Rather than doing this conversion by hand every time, see today's live gold rate per gram already calculated for you, or use the Purity Converter to move between karat, fineness and percent instantly. And to isolate exactly how much of a jeweler's quoted price is metal versus markup, the Jewelry Bill Breakdown tool does that decomposition directly." },
    ],
    relatedLinks: [
      { path: '/gold-rate-today', label: 'See today\'s live gold rate per gram' },
      { path: '/convert', label: 'Convert between karat, fineness and percent' },
      { path: '/bill-breakdown', label: 'Break down a jewelry bill into metal + markup' },
    ],
    updated: '2026-10-02',
    category: 'Metals',
    keywords: ['gold price per gram', 'gold price per gram today', 'gold price per gram in india', 'gold price per gram 22k'],
    faqs: [
      { q: 'What is the gold price per gram today?', a: 'It changes with live spot prices — MetalCalc\'s Gold Rate Today page shows it live, already converted from the per-ounce spot quote.' },
      { q: 'How do I convert gold price per ounce to per gram?', a: 'Divide the price per troy ounce by 31.1034768 — that\'s the exact number of grams in a troy ounce.' },
      { q: 'Why is gold price per gram different for 22k vs 24k?', a: 'Because 22k contains less pure gold by weight (91.67% vs 99.9%) — multiply the 24k per-gram price by the karat\'s purity fraction to get its value.' },
      { q: 'Is gold price per gram the same everywhere in the world?', a: 'The underlying international spot price is the same, but local prices can differ slightly due to currency conversion, import duties, and local market premiums.' },
      { q: 'Does gold price per gram include making charges?', a: 'No — spot price per gram is the raw metal value only. A jeweler\'s quoted price adds making charges and taxes on top.' },
    ],
  },
  {
    slug: '24k-vs-22k-gold-difference',
    title: '24k vs 22k Gold: What\'s the Actual Difference?',
    description: 'The real difference between 24k and 22k gold — purity, durability, color, and value — with the exact math.',
    h1: '24k vs 22k gold: what\'s the actual difference?',
    intro: 'The number after "k" isn\'t a grading scale — it\'s a fraction. Here\'s exactly what changes between 24k and 22k.',
    sections: [
      { p: "If you've shopped for gold jewelry, you've seen \"24k\" and \"22k\" stamped on pieces and probably assumed the number after \"k\" was just some kind of general quality grade, like a star rating. It's actually something much more precise: karat is literally a fraction out of 24, describing exactly how much of the metal is pure gold. Understanding that one fact unlocks everything else in this comparison." },
      { h2: 'Purity, in exact numbers' },
      { p: "24 karat means 24 parts out of 24 are gold — in other words, 99.9% pure gold, often written as .999 fineness. 22 karat means 22 parts out of 24 are gold, which works out to 22 ÷ 24 = 91.67% pure gold. The remaining roughly 8.3% in 22k is made up of other metals — usually copper and/or silver — deliberately mixed in as what's called an alloy." },
      { h2: 'Why anyone would deliberately dilute pure gold at all' },
      { p: "This sounds counterintuitive at first — why make gold less pure on purpose? The answer is durability. Pure gold is genuinely soft as a metal, which means 24k jewelry scratches, dents and deforms considerably more easily than jewelry made with some alloy mixed in. 22k (and lower karats like 18k, 14k, and so on) trade away a bit of purity specifically in exchange for added hardness and durability — which is exactly why most everyday jewelry you'll actually wear regularly isn't 24k, even though 24k is technically the \"purer\" option." },
      { h2: 'How the value difference actually works' },
      { p: "At the exact same weight, 22k gold is worth 91.67% of what 24k gold is worth in metal value — and this isn't some marketing discount, it's simply the real gold content ratio showing up as a price difference. A concrete way to picture this: a 10-gram chain made of 22k gold contains the same actual amount of pure gold as a 9.167-gram piece made of 24k gold would. The weight number on the scale looks different, but the underlying pure-gold content is equivalent." },
      { h2: "Does 24k look different from 22k?" },
      { p: "24k has gold's natural, deep yellow color in its purest form. 22k, with only a small amount of alloy mixed in, looks nearly identical to the eye in most lighting — but it can shift very slightly in tone depending on which specific alloy metal was used to make it: copper-based alloys tend to warm the tone slightly, while silver-based alloys tend to cool it slightly." },
      { h2: 'Which one should you actually buy?' },
      { p: "If you want jewelry you'll wear regularly — rings, bracelets, anything that sees daily wear and the occasional knock — 22k or lower generally makes more practical sense because of the added durability. If you're buying for pure investment purposes rather than to wear, 24k coins or bars are the more standard choice, since investment-grade gold is typically valued on purity alone rather than wearability. Neither one is objectively \"better\" — they're suited to different purposes." },
      { h2: 'Check the exact numbers for your own situation' },
      { p: "To convert any specific weight between 24k, 22k, 18k, 14k or 10k instantly, use the Purity Converter. And if you're ever curious what happens when pieces of different karats get melted down together — which doesn't simply average the two karat numbers — see how that blended math actually works." },
    ],
    relatedLinks: [
      { path: '/convert', label: 'Convert 24k value to 22k, 18k, 14k or 10k' },
      { path: '/alloy-mix', label: 'See what happens when purities are melted together' },
    ],
    updated: '2026-10-02',
    category: 'Metals',
    keywords: ['22k vs 24k gold', '22k vs 24k gold difference', '22k vs 24k gold which is best', '22k vs 24k gold resale value'],
    faqs: [
      { q: 'Which is better, 22k or 24k gold?', a: "Neither is universally 'better' — 24k is purer but softer, 22k trades some purity for durability, which is why most everyday jewelry is 22k or lower." },
      { q: 'What is the price difference between 22k and 24k gold?', a: '22k is worth 91.67% of 24k\'s value at the same weight — that\'s the exact gold-content ratio, not a marketing margin.' },
      { q: 'Does 22k gold look different from 24k?', a: 'Nearly identical in color, with a very slight tone shift depending on the alloy metal used — copper warms the tone, silver cools it.' },
      { q: 'Which has better resale value, 22k or 24k gold?', a: '24k generally resells closer to its full metal value since it\'s already near-pure; 22k resells at its proportional gold content, plus whatever making charges were already paid are typically not recovered either way.' },
      { q: 'Why is 24k gold not used for everyday jewelry?', a: 'Pure gold is soft and scratches/deforms easily — alloying with copper or silver (making it 22k or lower) adds hardness and durability for daily wear.' },
    ],
  },
  {
    slug: 'best-time-to-buy-gold',
    title: 'Is There a "Best Time" to Buy Gold?',
    description: 'Why timing gold purchases is harder than it sounds, and two practical frameworks that don\'t rely on predicting price direction.',
    h1: 'Is there a "best time" to buy gold?',
    intro: 'Short answer: nobody reliably calls the bottom. Here\'s a more useful way to think about it.',
    sections: [
      { p: "Almost everyone who thinks about buying gold eventually wonders the same thing: should I wait, or is now actually a fine time to buy? It's a completely reasonable question, and the honest short answer is that nobody — no expert, no analyst, no chart pattern — reliably calls the exact bottom of any asset's price, gold included. Rather than leave you with just that discouraging answer, this guide walks through why timing is genuinely hard, and two practical approaches that let you move forward without needing to solve an unsolvable problem." },
      { h2: 'Why timing gold purchases is genuinely difficult, not just unlucky' },
      { p: "Gold's price reacts to a whole set of macro-level forces that are themselves fundamentally unpredictable — real interest rates (the interest rate after accounting for inflation), currency strength, geopolitical risk events, and how much central banks around the world happen to be buying or selling at any given time. Anyone confidently claiming they have a reliable \"best time to buy\" signal for gold is overstating their actual edge — and that includes seasonal patterns some people point to (like \"gold tends to do well around certain months\"), which turn out to be weak and inconsistent when you actually check them year over year." },
      { h2: "Framework 1: stop trying to pick a bottom, use dollar-cost averaging instead" },
      { p: "Rather than trying to identify the single best moment to buy, you can sidestep that decision entirely: buy a fixed amount on a fixed schedule — say, monthly — completely regardless of what the price happens to be doing that month. This approach, called dollar-cost averaging, removes the timing decision from the equation altogether and naturally smooths out your average purchase price over time, since you end up buying a bit more when prices dip and a bit less when they're elevated. For the fuller mechanics of how and why this works (the same math applies whether you're buying gold or crypto), see the full breakdown of whether dollar-cost averaging actually works." },
      { h2: 'Framework 2: stop asking "when" and start asking "how much"' },
      { p: 'A second, equally practical approach: instead of asking "is now a good time to buy gold," reframe the question entirely to "how much do I need to buy each month to reach a specific weight of gold by a specific target date." This reframing sidesteps the timing question completely, because you\'re now planning around a goal and a schedule rather than trying to predict price movements. The Savings Goal Projector answers this directly using live prices, turning a vague intention into an actual monthly number.' },
      { h2: 'The one piece of context genuinely worth checking before you buy' },
      { p: "While no single number should dictate your decision, the gold-silver ratio and how far gold's current price sits from its recent range can give you useful context on whether you're buying at a relatively high or relatively low point compared to recent history. This isn't a signal to act on by itself — but it's a reasonable extra data point to glance at alongside whichever framework above you're actually using to decide how much and how often to buy." },
      { h2: 'Putting it together: a simple, repeatable approach' },
      { p: "Pick either a recurring schedule (dollar-cost averaging) or a weight-and-date goal (the Savings Goal Projector), glance at the current gold-silver ratio for context rather than as a trigger, and then actually stick to your plan rather than waiting indefinitely for a \"perfect\" entry point that may never clearly arrive." },
    ],
    relatedLinks: [
      { path: '/savings-goal', label: 'Plan monthly buys toward a weight goal' },
      { path: '/blog/dollar-cost-averaging-crypto-does-it-work', label: 'Read: does DCA actually work?' },
      { path: '/gold-vs-silver-investment', label: 'Check the live gold-silver ratio' },
    ],
    updated: '2026-10-02',
    category: 'Metals',
    keywords: ['best time to buy gold', 'when to buy gold', 'gold investment timing'],
    faqs: [
      { q: 'Is there a best month to buy gold?', a: 'Seasonal patterns are weak and inconsistent year to year — not reliable enough to plan a purchase around.' },
      { q: 'How do I decide when to buy gold without timing the market?', a: 'Two practical options: dollar-cost average a fixed amount on a schedule, or set a weight goal and a monthly plan to reach it — both skip the timing decision entirely.' },
      { q: 'Does the gold-silver ratio tell me when to buy?', a: "It gives relative-pricing context, not a buy signal on its own — useful alongside a plan, not a replacement for one." },
      { q: 'Should I wait for a dip to buy gold?', a: 'Waiting for a dip that may not come is a common reason people never actually buy — a scheduled plan avoids that specific trap.' },
      { q: 'Is gold a good long-term investment regardless of timing?', a: 'That depends on your own goals and risk tolerance — this page is about removing the timing question, not making an investment recommendation.' },
    ],
  },
  {
    slug: 'gold-investment-for-beginners',
    title: 'Gold Investment for Beginners: A Practical Starting Guide',
    description: 'The practical basics of investing in physical gold — forms, purity, storage, and how to actually track what you own.',
    h1: 'Gold investment for beginners',
    intro: 'No hype, just the practical basics of buying and holding physical gold.',
    sections: [
      { p: "If you're thinking about buying gold for the first time as an actual investment — not just a piece of jewelry — it helps to walk through the practical basics before you spend any money, rather than figuring it out after the fact. This guide skips the hype and sticks to what actually matters: what form to buy, why purity matters more than you might expect, what it genuinely costs to hold physical gold over time, and how to actually keep track of what you own." },
      { h2: 'What form of gold should you actually buy?' },
      { p: "Coins and small bars from recognized, reputable mints are generally the most liquid physical forms of gold — meaning they're the easiest to verify as genuine and the easiest to resell later when you want to. Jewelry, by contrast, carries making charges (the labor and design cost of crafting it) that you simply don't get back when you go to resell it — which makes jewelry a relatively poor vehicle for pure investment, even though it remains an extremely common way people end up holding gold anyway, often for sentimental or cultural reasons rather than investment ones." },
      { h2: 'Why purity matters more for investment-grade gold than you might think' },
      { p: "Gold specifically bought for investment — coins and bars — is typically .999 or .9999 fine, which is essentially the 24-karat equivalent: as pure as gold practically gets. Lower-karat jewelry gold is perfectly fine to own and wear, but when you eventually go to resell it, its value gets discounted for two separate reasons: it simply contains less actual gold by weight than 24k does, and you won't recover the making charges you already paid when it was originally crafted. Neither of these makes jewelry gold a bad thing to own — it just means you shouldn't expect it to perform identically to pure investment-grade gold." },
      { h2: "Storage and insurance are real, ongoing costs — not a one-time afterthought" },
      { p: "Here's something beginners frequently don't think about until later: physical gold needs to actually be stored somewhere secure, whether that's a home safe, a bank safe deposit box, or a specialized depository — and any option beyond a basic home safe typically comes with an ongoing fee. On top of storage, a holding large enough to matter is genuinely worth insuring, since standard home insurance policies usually cap jewelry and precious-metals coverage well below what a serious holding is worth. Both of these cost real money over time, so it's worth running the actual numbers with the Storage & Insurance Cost Calculator before assuming physical gold is simply \"free\" to hold once you've bought it." },
      { h2: 'A few realistic starting scenarios' },
      { p: "You're setting aside a small, regular amount each month specifically to build up a gold position over time, rather than making one large purchase. You've received gold as a gift or inheritance and want to understand what you actually have before deciding whether to keep, sell, or add to it. You're diversifying an existing stock or crypto portfolio and want a tangible asset that behaves differently from the rest of what you own. In each of these, the practical steps above — choosing the right form, understanding purity, and planning for storage costs — apply the same way." },
      { h2: 'Track it like an actual portfolio, not a drawer you forget about' },
      { p: "Once you own gold, the single most useful habit is logging the weight, purity, and what you actually paid for each piece — that's what lets you see your real gain or loss over time, instead of just having a vague sense that \"gold has gone up\" without knowing what that actually means for your specific holdings. My Holdings does exactly this with live pricing, and shows a diversification score automatically if you also hold silver or platinum alongside your gold." },
    ],
    relatedLinks: [
      { path: '/holdings', label: 'Track your holdings with live value' },
      { path: '/storage-cost', label: 'Estimate storage & insurance cost' },
      { path: '/how-to-calculate-gold-purity', label: 'How to calculate gold purity' },
    ],
    updated: '2026-10-02',
    category: 'Metals',
    keywords: ['gold investment for beginners', 'how to invest in gold', 'buying gold for the first time'],
    faqs: [
      { q: 'What form of gold is best for a beginner investor?', a: 'Coins and small bars from recognized mints are the most liquid and easiest to verify/resell — jewelry carries making charges you don\'t recover on resale.' },
      { q: 'What purity should investment gold be?', a: 'Typically .999 or .9999 fine (24k-equivalent) for coins/bars — lower-karat jewelry gold is fine to own but resells at a discount for both lower content and unrecovered making charges.' },
      { q: 'Does gold cost money to hold?', a: 'Yes — storage and insurance are real ongoing costs for a serious physical holding, unlike a number in a brokerage app.' },
      { q: 'How do I track my gold investment over time?', a: "Log the weight, purity and price paid per item so you can see real gain/loss — a vague sense of 'gold went up' isn't the same as knowing your actual return." },
      { q: 'How much gold should a beginner buy?', a: 'That depends on your own goals and risk tolerance — this guide covers the practical mechanics of buying/holding, not a specific allocation recommendation.' },
    ],
  },
  {
    slug: 'silver-investment-guide',
    title: 'Silver Investment Guide: What Makes It Different From Gold',
    description: 'What actually makes silver a different investment than gold — industrial demand, volatility, storage bulk, and liquidity.',
    h1: 'Silver investment guide',
    intro: 'Silver isn\'t "cheap gold" — it behaves differently for structural reasons worth understanding before you buy.',
    sections: [
      { p: "It's tempting to think of silver as just a cheaper, more accessible version of gold — same idea, smaller price tag. That assumption will actually cause real surprises once you own some, because silver behaves genuinely differently from gold for reasons that go beyond price alone. Understanding those structural differences before you buy will save you from being caught off guard later." },
      { h2: 'The key structural difference: industrial demand' },
      { p: "A meaningful share of overall silver demand comes from actual industrial uses — electronics, solar panel manufacturing, and various medical applications, among others — not just investment and jewelry demand the way gold's demand is mostly structured. This extra demand driver is a large part of why silver tends to be noticeably more volatile than gold in both directions: it can rally harder than gold during good times, and fall further during downturns, because its price reflects both investor sentiment and the health of the broader industrial/manufacturing economy at the same time." },
      { h2: 'Storage takes up a lot more physical room than you might expect' },
      { p: "Silver is worth far less per gram than gold is. That means the exact same dollar amount invested in silver takes up dramatically more physical space and weight than the equivalent amount in gold would. If you're planning to store your own silver yourself — rather than through some kind of custodial account — this is a genuinely practical consideration, not just a minor detail: a meaningful silver holding can mean several heavy, bulky bars or a large number of coins, rather than something that fits easily in a small safe." },
      { h2: 'Liquidity and spreads work a bit differently too' },
      { p: "Gold generally has tighter buy/sell spreads (the gap between what a dealer will pay you to buy your gold and what they'll sell it to you for) and wider acceptance for resale almost anywhere in the world. Silver dealer spreads can be noticeably wider, particularly for smaller or less-recognized bar and coin formats — meaning you may give up more value on the way in and out of a silver position compared to an equivalent gold one." },
      { h2: 'A few situations where understanding this actually matters' },
      { p: "You're deciding how to split a fixed investment budget between gold and silver and want to understand what you're actually trading off, not just which one is \"cheaper\" per unit. You're planning your own home storage and need to realistically estimate how much physical space a silver holding will require. You're thinking about how quickly you might need to liquidate part of a metals holding in an emergency, and want to know which metal resells more easily. In each case, these structural differences — not just the sticker price — are what should actually drive your decision." },
      { h2: 'How to think about splitting an allocation between the two' },
      { p: "The gold-silver ratio gives you useful context on how the two metals are currently priced relative to each other, but your actual position size should also weigh your own tolerance for volatility (remember, silver swings harder in both directions) and how easily you might need to liquidate part of your holding on short notice. Track both metals together, and you'll get a real diversification score across your full metals holding on My Holdings — a clearer picture than just eyeballing two separate numbers." },
    ],
    relatedLinks: [
      { path: '/gold-vs-silver-investment', label: 'Compare gold vs silver directly' },
      { path: '/holdings', label: 'Track a mixed metals portfolio' },
      { path: '/blog/gold-silver-ratio-explained', label: 'Read: the gold-silver ratio explained' },
    ],
    updated: '2026-10-02',
    category: 'Metals',
    keywords: ['how to invest in silver', 'silver investment guide', 'silver vs gold investment'],
    faqs: [
      { q: 'Why is silver more volatile than gold?', a: 'Silver has real industrial demand (electronics, solar) on top of investment demand, which is an extra demand driver gold mostly lacks — that extra driver adds volatility in both directions.' },
      { q: 'Is silver harder to store than gold?', a: "Yes in practical terms — silver is worth far less per gram than gold, so the same dollar amount takes up much more physical space and weight." },
      { q: 'Is silver less liquid than gold?', a: 'Generally yes — gold has tighter buy/sell spreads and wider resale acceptance; silver dealer spreads can be wider, especially for smaller or less-recognized formats.' },
      { q: 'How much silver should I hold vs gold?', a: 'The gold-silver ratio gives pricing context, but your own volatility tolerance and liquidity needs matter just as much — there\'s no single correct split.' },
      { q: 'Can I track silver alongside gold in one place?', a: 'Yes — MetalCalc\'s Holdings page tracks both together with live value and a diversification score across your metals.' },
    ],
  },
  {
    slug: 'crypto-portfolio-diversification-guide',
    title: 'Crypto Portfolio Diversification: What Actually Reduces Risk',
    description: 'Why holding many coins doesn\'t automatically mean you\'re diversified, and how to actually check.',
    h1: 'Crypto portfolio diversification: what actually reduces risk',
    intro: 'Holding 10 coins instead of 1 feels diversified. It often isn\'t.',
    sections: [
      { p: "Holding ten different coins instead of just one feels like it should be safer — more spread out, less risky. In practice, that feeling is very often wrong, and understanding why is one of the more important things a crypto investor can learn early on." },
      { h2: 'The problem with judging diversification by allocation alone' },
      { p: "A diversification score based purely on allocation — how your capital is split up, using a measure like HHI (Herfindahl-Hirschman Index) — tells you whether your money is spread evenly across positions or heavily concentrated in just one or two. That's a genuinely useful thing to know. But here's the limitation: it only looks at position sizing, meaning how much money is in each coin. It says absolutely nothing about whether those different positions actually move independently of each other day to day." },
      { h2: 'The correlation problem that a pure allocation score completely misses' },
      { p: "Here's the uncomfortable reality about crypto specifically: most large-cap crypto assets move together on the same macro \"risk-on, risk-off\" days — sometimes agreeing on direction more than 70% of the time. What this means in practice is that ten different altcoins that all basically track Bitcoin's overall mood aren't really ten independent bets, the way owning ten unrelated companies' stocks might be — they're much closer to one single leveraged bet on the same underlying thing, just spread across ten different ticker symbols. This is exactly why checking correlation matters just as much as checking your allocation spread." },
      { h2: 'A concrete way this catches people off guard' },
      { p: "Imagine you've split your crypto holdings evenly across ten different coins, and your allocation-based diversification score comes back looking great — high, evenly spread, exactly what you'd hope to see. Then the broader crypto market has one bad week, and nine out of your ten coins fall together on the same days, because they were all quietly following the same overall market mood the whole time. The diversification score didn't lie to you — your money genuinely was spread out — but it also didn't warn you that \"spread out\" and \"actually protected\" are two different things." },
      { h2: 'What a genuinely complete diversification check actually looks like' },
      { p: "You need two numbers together, not just one: an allocation-based diversification score (available across your metals, stocks and crypto on the Net Worth page), and a same-direction correlation percentage across your specific crypto coins (available on the Crypto page's watchlist tab, which shows what percentage of days each pair of coins actually moved the same direction). Seeing high correlation between coins your allocation score calls \"diversified\" is a genuine flag worth acting on — maybe by consolidating into fewer, more differentiated positions — not something to quietly ignore as a footnote." },
    ],
    relatedLinks: [
      { path: '/net-worth', label: 'See your cross-asset diversification score' },
      { path: '/crypto', label: 'Check correlation across your watchlist' },
    ],
    updated: '2026-10-02',
    category: 'Markets',
    keywords: ['crypto portfolio tracker', 'crypto portfolio diversification', 'crypto diversification app'],
    faqs: [
      { q: 'Does holding more coins mean I am more diversified?', a: 'Not necessarily — an allocation score can look spread-out while the coins themselves move together most days, which is not real diversification.' },
      { q: 'How correlated are most crypto assets?', a: 'Often highly — many altcoins track Bitcoin\'s overall mood on risk-on/risk-off days, sometimes moving the same direction 70%+ of days.' },
      { q: 'What two numbers should I check for real crypto diversification?', a: 'An allocation-based diversification score (how spread your capital is) and a same-direction correlation percentage across your specific coins (whether they actually move independently).' },
      { q: 'Can I check correlation between my crypto holdings for free?', a: "Yes — MetalCalc's Crypto page includes a same-direction correlation check across your watchlist, no account needed." },
      { q: 'Is a high correlation between my coins always a problem?', a: 'Not necessarily a problem, but it is a flag worth knowing about — it means those coins are not protecting you from each other in a downturn, which matters if that was the goal.' },
    ],
  },
  {
    slug: 'understanding-stock-trade-signals',
    title: 'Understanding Automated Stock Trade Signals (What They Can\'t Tell You)',
    description: 'How rule-based buy/sell signals are actually built, what factors go in, and their honest limitations.',
    h1: 'Understanding automated stock trade signals',
    intro: 'A "Buy" or "Sell" label feels authoritative. Here\'s what\'s actually behind one.',
    sections: [
      { p: "Seeing a stock labeled \"Buy\" or \"Sell\" on a finance website can feel authoritative — like some confident expert system has figured something out that you haven't. In reality, what's usually behind that label is much more mechanical and far more explainable than it looks at first glance, and understanding exactly what's going on behind the label makes it genuinely more useful, not less." },
      { h2: "It's a weighted scorecard, not a prediction about the future" },
      { p: "A rule-based trade signal combines several individual factors into one combined score — common inputs include the PEG ratio (a valuation measure accounting for growth), EPS and revenue growth figures, where the stock currently sits within its 52-week price range, and recent price momentum. That combined score then gets converted into a simple Buy, Sell, or Hold label. The key thing to understand: no single factor alone decides the final label, and critically, no individual factor is actually claiming to predict what will happen next — each one is simply describing a fact about where things stand today." },
      { h2: 'Why 52-week range position specifically gets used as a stand-in' },
      { p: "Where a stock currently sits within its 52-week price range — closer to its yearly low versus closer to its yearly high — is used as a rough, indirect proxy for demand and supply pressure, specifically in situations where more detailed, real order-flow or price-action data simply isn't available. It's important to understand this is not the same thing as a proper technical support or resistance level, which would be built from actual historical price-action data showing a level genuinely held before. Treat 52-week range position as a coarse, approximate signal — useful context, not precise measurement." },
      { h2: "What these automated signals structurally cannot see, no matter how good the formula is" },
      { p: "These signals have no way of knowing about news that hasn't happened yet — an earnings surprise, a product recall, a regulatory change — because they're built entirely from historical and current data, not future events. They also don't price in company-specific risks beyond whatever shows up in the growth and valuation numbers being used, and they can flip from one label to another fairly quickly if the underlying data changes, which can look jarring if you're expecting a signal to be a stable, long-term verdict rather than a current snapshot. A composite score like this is genuinely useful as a starting point for your own research — it is not a substitute for doing that research." },
      { h2: 'A simple way to use a signal like this responsibly' },
      { p: "Treat the label itself as a quick summary, but always read the reasoning behind it before acting — the specific factors that pushed the score toward Buy or Sell tell you far more than the single word does on its own, and they let you judge for yourself whether those specific factors actually matter for your own situation." },
      { h2: 'Where to actually see one in practice' },
      { p: "MetalCalc's Stocks page combines these factors transparently and shows the specific reasoning behind each Buy or Sell call it generates — read the accompanying \"reason\" text each time, not just the headline label on its own." },
    ],
    relatedLinks: [
      { path: '/stocks', label: 'See live trade signals with reasoning' },
      { path: '/blog/peg-ratio-explained', label: 'Read: PEG ratio explained' },
    ],
    updated: '2026-10-02',
    category: 'Markets',
    keywords: ['stock trade signal', 'automated buy sell signal', 'stock screener signal'],
    faqs: [
      { q: 'How do automated stock trade signals actually work?', a: 'They combine several factors — like PEG ratio, growth rates, and 52-week range position — into one weighted score, then convert that score into a Buy/Sell/Hold label.' },
      { q: 'Can I trust an automated Buy/Sell signal?', a: "Treat it as a starting point for research, not a substitute for it — it can't see news that hasn't happened yet and can flip quickly if the underlying data changes." },
      { q: 'What is the 52-week range position in a trade signal?', a: "A rough proxy for demand/supply — where a stock sits between its yearly low and high — used when real price-action data isn't available." },
      { q: 'Why does MetalCalc show a reason with each trade signal?', a: "So the label isn't a black box — you can see exactly which factors (PEG, growth, momentum) drove the Buy/Sell/Hold call." },
      { q: 'Are stock trade signals the same as financial advice?', a: 'No — they are a transparent, rule-based scorecard from public data, not personalized financial advice.' },
    ],
  },
  {
    slug: 'savings-goal-vs-lump-sum-gold',
    title: 'Savings Goal vs Lump Sum: Two Ways to Build a Gold Position',
    description: 'The tradeoffs between saving toward a gold weight goal monthly versus buying a lump sum today.',
    h1: 'Savings goal vs lump sum: two ways to build a gold position',
    intro: 'Both get you to a target weight of gold. They get there very differently.',
    sections: [
      { p: "If you have a specific amount of gold you'd eventually like to own — say, a target weight for a future purchase, a gift, or just a personal savings goal — there are really two fundamentally different ways to get there. Both end up at the same destination, a specific weight of gold in your possession, but they get there in very different ways, with different tradeoffs worth understanding before you pick one." },
      { h2: 'Path 1: buy the full amount today, all at once' },
      { p: "This is the lump-sum approach: you buy the entire target weight today, at today's price, in one single purchase. It's simple to execute and easy to understand. If gold's price happens to rise after you buy, you're fully exposed to that entire gain starting from day one, since all your money went in at once. The tradeoff, though, is symmetric: you're equally fully exposed if the price happens to fall shortly after you buy. This path also requires having the complete amount of money available right now, in one go, rather than being able to spread the cost out over time." },
      { h2: 'Path 2: build toward the goal gradually, a bit each month' },
      { p: "This is the savings-goal approach: you set a target weight and a target date, then figure out a monthly contribution amount, and buy smaller amounts regularly over time until you reach the full target. This naturally spreads your actual entry price across many different points in time instead of a single one, and — just as importantly — it doesn't require having the full capital available upfront. This makes it a genuinely practical option if you're building toward the goal gradually out of ongoing income, rather than having a lump sum (like a bonus or inheritance) ready to deploy all at once." },
      { h2: 'Which path actually fits your own situation' },
      { p: 'If you already have the full capital sitting available and you don\'t need that money for anything else in the meantime, a lump sum is simpler to execute and carries no "waiting" cost — there\'s no reason to delay if the money is just sitting idle regardless. On the other hand, if you\'re accumulating the funds gradually from your regular income rather than from an existing lump of savings, a savings-goal plan is simply the realistic, achievable option for you — regardless of which approach would have mathematically performed better in hindsight after the fact, since hindsight isn\'t available to you when you\'re actually deciding.' },
      { h2: 'A few concrete situations where each path makes sense' },
      { p: "You just received a bonus or inheritance and want to convert part of it into gold right away — lump sum fits naturally here. You're setting aside a portion of each paycheck specifically toward a future gold purchase — the savings-goal path fits here instead. You're not sure which to pick and want to see the actual numbers side by side before deciding — that's exactly what planning with live prices helps clarify." },
      { h2: 'Plan either approach using live, current numbers' },
      { p: "The Savings Goal Projector shows you exactly how long a fixed monthly contribution amount will take to reach a specific weight target, using today's actual live prices — genuinely useful for planning purposes even if you ultimately decide to buy some or all of it as a lump sum later instead." },
    ],
    relatedLinks: [
      { path: '/savings-goal', label: 'Project your own savings goal timeline' },
      { path: '/blog/dollar-cost-averaging-crypto-does-it-work', label: 'Read: does DCA actually work?' },
    ],
    updated: '2026-10-02',
    category: 'Metals',
    keywords: ['savings goal calculator', 'savings goal calculator monthly', 'gold savings plan'],
    faqs: [
      { q: 'Is it better to buy gold as a lump sum or save monthly toward it?', a: 'Lump sum is simpler and fully exposed to gains/losses from day one; a monthly savings plan spreads entries over time and doesn\'t need the full capital upfront — the right one depends on whether you have the capital now or are building from income.' },
      { q: 'How do I plan monthly savings toward a gold weight goal?', a: "Set a target weight and date, then MetalCalc's Savings Goal Projector calculates the monthly amount needed at current prices." },
      { q: 'Does a savings goal plan guarantee I reach my target weight?', a: 'It projects the required contribution at today\'s prices — if prices rise, the same monthly amount buys less weight than projected, and vice versa if prices fall.' },
      { q: 'Can I switch from a savings plan to a lump sum later?', a: 'Yes — planning with a savings goal doesn\'t lock you in; it\'s a useful reference point even if you end up buying some of it in a lump sum later.' },
      { q: 'Does this work for silver too?', a: 'Yes — the Savings Goal Projector works for any supported metal, not just gold.' },
    ],
  },
  {
    slug: 'jewelry-making-charges-explained',
    title: 'Jewelry Making Charges Explained: What You\'re Actually Paying For',
    description: 'What making charges cover, typical structures (flat vs percentage), and how to check if a quoted price is fair.',
    h1: 'Jewelry making charges explained',
    intro: 'The gap between a piece\'s metal value and its price tag has a name — here\'s what it actually covers.',
    sections: [
      { p: "If you've ever looked at a jewelry bill and noticed a separate line item called \"making charges\" sitting next to the metal value, and wondered exactly what that extra charge is actually paying for, you're asking a genuinely useful question. The gap between a piece's raw metal value and its full price tag has a name, and understanding what it actually covers helps you judge whether a specific quote feels fair." },
      { h2: 'What making charges are actually paying for' },
      { p: "Making charges cover a combination of things: the labor involved in actually shaping raw metal into a finished design, the complexity of that specific design, an allowance for the small amount of metal inevitably lost as waste during the crafting process, and the retailer's own profit margin on top of all that. An intricate, handmade design commands meaningfully higher making charges than a simple, machine-made piece, simply because more skilled labor and more material loss genuinely goes into producing it." },
      { h2: 'Two different ways jewelers structure this charge' },
      { p: "Some jewelers charge a flat amount per gram of metal, regardless of how complex the specific design is. Others instead charge a percentage of the metal's value — and this percentage is often set higher for more elaborate designs to reflect the extra work involved. Here's a detail worth knowing before you compare two quotes: a percentage-based making charge costs more in absolute currency terms on a day when the underlying metal price happens to be higher — for the exact same design. This matters if you're comparing a quote you got today against one you got weeks ago; the design and the percentage might be identical, but the final number can differ simply because metal prices moved in between." },
      { h2: 'How to actually check whether a specific quote feels reasonable' },
      { p: "Start by backing out the pure metal value using that day's spot price and the piece's purity — this tells you what the raw metal alone is worth, with no markup. Then look at what percentage the making charge plus any tax represents of the total bill you were quoted. There's no single universal \"fair\" percentage that applies across the board — it genuinely varies a great deal depending on design complexity, local market norms, and the specific jeweler. But once you can see the actual percentage in front of you, you can meaningfully compare quotes across different jewelers and negotiate from real information, instead of just guessing at whether a number feels high or low." },
      { h2: 'A simple way to use this when you\'re actually shopping' },
      { p: "Ask directly whether the making charge is flat-per-gram or percentage-based before comparing two quotes — that single question prevents you from comparing numbers that aren't actually apples-to-apples. Once you know the structure, do the math above for each quote to see the real percentage each jeweler is actually charging you." },
      { h2: 'Check your own numbers' },
      { p: "Rather than estimating this by hand, the Jewelry Bill Breakdown tool separates any quoted price into metal value, making charges, and tax automatically — and the Melt vs Retail Markup Checker shows the total markup over pure melt value directly, if that's the simpler comparison you want." },
    ],
    relatedLinks: [
      { path: '/bill-breakdown', label: 'Break down a jewelry bill into metal + markup' },
      { path: '/melt-check', label: 'Check markup over pure melt value' },
    ],
    updated: '2026-10-02',
    category: 'Tools',
    keywords: ['jewelry making charges', 'jewellery making charges per gram', 'jewellery making charges gst rate'],
    faqs: [
      { q: 'What are jewelry making charges?', a: "The labor, design complexity and wastage cost added on top of a piece's pure metal value — plus the retailer's margin." },
      { q: 'Are jewelry making charges a flat fee or a percentage?', a: 'Both structures exist — some jewelers charge a flat amount per gram, others a percentage of the metal value; a percentage-based charge costs more in absolute terms on an expensive-metal day.' },
      { q: 'How much are typical making charges in India?', a: 'It varies widely by jeweler, design complexity and city — there is no single standard percentage, which is exactly why checking the actual breakdown matters.' },
      { q: 'How do I check if my jewelry making charge is fair?', a: "Back out the pure metal value at today's spot price and purity, then see what percentage the making charge + tax represents of the total bill — compare that number across jewelers." },
      { q: 'Do making charges apply to GST too?', a: 'Making charges are typically taxed, often at a different GST rate than the metal value itself — check your specific bill\'s breakdown rather than assuming one combined rate.' },
    ],
  },
  {
    slug: 'net-worth-tracking-guide',
    title: 'Tracking Net Worth Across Metals, Stocks and Crypto in One Place',
    description: 'Why fragmented net worth tracking hides your real risk, and how to see a combined number without a brokerage aggregator.',
    h1: 'Tracking net worth across metals, stocks and crypto',
    intro: 'Most people\'s wealth is scattered across a jewelry box, a brokerage app, and a crypto exchange — each showing a number in isolation.',
    sections: [
      { p: "Think about where your actual wealth lives right now. For a lot of people, it's genuinely scattered: some gold jewelry sitting in a drawer or a locker, a stock portfolio inside a brokerage app, maybe a crypto wallet or exchange account, and possibly cash savings somewhere else entirely. Each of those shows you its own number, in its own app, completely disconnected from the others. This guide is about why that fragmentation actually hides risk from you, and how to see one honest, combined number instead." },
      { h2: 'Why seeing one combined number actually matters' },
      { p: "Here's a very concrete example of the problem: you check your brokerage app and see your stocks are up 8% this month. You check your crypto exchange and see you're down 15% over the same period. Looked at separately, these feel like two unrelated facts about two unrelated parts of your life. But your actual total net worth might be roughly flat once you combine them — or worse, one of those two asset classes might be so much larger than the other in absolute dollar terms that it's dominating your overall risk far more than the simple percentage numbers make it feel like. A combined total is the only genuinely honest picture of where you actually stand financially, because percentages in isolation can be quietly misleading about what really matters: the real dollar amount at stake in each part of your portfolio." },
      { h2: "What should actually count, beyond just today's account balances" },
      { p: "A complete picture needs more than just \"what's my stuff worth right now.\" Unrealized gains — the paper profit or loss on positions you still currently hold — are part of your real financial position. But so are realized gains and losses: the actual profit or loss you locked in on things you've already sold in the past. If you only ever look at your current holdings and ignore past realized gains and losses, you're working from an incomplete picture of your actual financial trajectory, not just a current snapshot." },
      { h2: 'The diversification check that matters more than the total number itself' },
      { p: "Once you can actually see a combined total, the next genuinely useful question is whether that total is actually spread across different asset classes, or quietly concentrated in just one without you fully realizing it. This is exactly what a diversification score is for — a number based on how evenly your value is spread across categories like metals, stocks and crypto, rather than just a vague sense of \"well, I own three different kinds of things, so I must be fine.\" Owning three different asset types says nothing about whether your money is actually spread evenly across them, or whether 90% of it happens to sit in just one." },
      { h2: 'A realistic example of why this catches people off guard' },
      { p: "Imagine someone who feels reasonably diversified because they own gold, some stocks, and a bit of crypto. When they actually add everything up, they discover 85% of their total net worth is sitting in one particular stock position they built up gradually over several years without really noticing how large it had become relative to everything else. The gold and crypto, while real and present, are small enough in dollar terms that they're barely moving the overall risk picture at all. Without combining everything into one view, this kind of concentration is very easy to miss — each individual account looks fine on its own, and the imbalance only becomes visible once everything is actually added together." },
      { h2: 'Keeping track of all this without linking your actual bank and brokerage accounts' },
      { p: "You might reasonably assume that getting one combined view requires some kind of bank-level account-linking service, the type that asks for your actual login credentials to pull live balances automatically. That's not the only option, and for many people it's not a comfortable one either. This entire approach works from manually-entered holdings and portfolios instead — you enter what you own (weight and purity for metals, quantity and purchase price for stocks and crypto), and live market prices do the rest of the work for you, with no bank-level account linking required at any point." },
      { h2: 'A few situations where this genuinely helps' },
      { p: "You're deciding whether to buy more of an asset class and want to know your real current exposure before adding to it. You're planning for a major life event — a move, a large purchase, retirement — and need an honest combined number, not three separate app screenshots. You suspect one asset class has quietly grown to dominate your portfolio and want to actually confirm it with real numbers instead of a vague feeling. You simply want one place to check your overall financial position periodically instead of opening three or four different apps each time." },
      { h2: 'One practical habit worth adopting: back it up regularly' },
      { p: "Because this entire system works from data stored only in your own browser — genuinely nowhere else, no server copy — it's worth building the habit of backing up your data periodically, particularly before clearing your browser's data or switching to a new device. A quick, regular backup is a small habit that protects a genuinely useful picture of your finances from being lost to something as mundane as clearing your cache." },
    ],
    relatedLinks: [
      { path: '/net-worth', label: 'See your combined net worth + P&L' },
      { path: '/backup', label: 'Back up your data' },
    ],
    updated: '2026-10-02',
    category: 'Markets',
    keywords: ['net worth tracker', 'net worth tracker app', 'net worth tracker spreadsheet'],
    faqs: [
      { q: 'Why track net worth across metals, stocks and crypto together?', a: 'Seeing each asset class separately hides whether your total is actually flat and whether one asset class dominates your risk more than you realize — a combined number is the honest picture.' },
      { q: 'Do I need a spreadsheet to track net worth?', a: "No — MetalCalc tracks it from your manually-entered Holdings, Stock and Crypto portfolios automatically, no spreadsheet or bank-level account linking required." },
      { q: 'Does net worth tracking include realized gains from things I already sold?', a: "Yes — both unrealized gains on open positions and realized gains from past sales count toward your actual financial position." },
      { q: 'Is my net worth data stored on a server?', a: 'No — everything is stored only in your browser; back it up regularly using the Backup & Restore tool.' },
      { q: 'Can I see a diversification score alongside my net worth?', a: 'Yes — the Net Worth page shows a diversification score alongside the combined total, based on how evenly value is spread across asset classes.' },
    ],
  },
]

export function getLandingPageBySlug(slug) {
  return LANDING_PAGES.find((p) => p.slug === slug) ?? null
}
