export const RANKING_CATEGORIES = ['AI', 'Semiconductor', 'Tech']

// Curated, not literally "all" AI/Semi/Tech stocks — Finnhub's free tier caps at
// 60 calls/min on a single API key shared by every visitor of this deployed site
// (VITE_ env vars are public). 2 calls/stock (quote + metrics) means this list's
// size directly sets the per-load call count — see useStockRankings.js for the
// batching this requires even at this size.
export const RANKING_STOCKS = [
  { symbol: 'NVDA', name: 'Nvidia', category: 'AI' },
  { symbol: 'PLTR', name: 'Palantir', category: 'AI' },
  { symbol: 'MSFT', name: 'Microsoft', category: 'AI' },
  { symbol: 'GOOGL', name: 'Alphabet', category: 'AI' },
  { symbol: 'META', name: 'Meta Platforms', category: 'AI' },
  { symbol: 'AMD', name: 'Advanced Micro Devices', category: 'AI' },
  { symbol: 'SNOW', name: 'Snowflake', category: 'AI' },
  { symbol: 'CRM', name: 'Salesforce', category: 'AI' },
  { symbol: 'NOW', name: 'ServiceNow', category: 'AI' },
  { symbol: 'ADBE', name: 'Adobe', category: 'AI' },
  { symbol: 'PATH', name: 'UiPath', category: 'AI' },
  { symbol: 'AI', name: 'C3.ai', category: 'AI' },

  { symbol: 'AVGO', name: 'Broadcom', category: 'Semiconductor' },
  { symbol: 'TSM', name: 'Taiwan Semiconductor', category: 'Semiconductor' },
  { symbol: 'QCOM', name: 'Qualcomm', category: 'Semiconductor' },
  { symbol: 'INTC', name: 'Intel', category: 'Semiconductor' },
  { symbol: 'MU', name: 'Micron Technology', category: 'Semiconductor' },
  { symbol: 'ASML', name: 'ASML Holding', category: 'Semiconductor' },
  { symbol: 'TXN', name: 'Texas Instruments', category: 'Semiconductor' },
  { symbol: 'LRCX', name: 'Lam Research', category: 'Semiconductor' },
  { symbol: 'KLAC', name: 'KLA Corporation', category: 'Semiconductor' },
  { symbol: 'AMAT', name: 'Applied Materials', category: 'Semiconductor' },
  { symbol: 'ON', name: 'ON Semiconductor', category: 'Semiconductor' },
  { symbol: 'MRVL', name: 'Marvell Technology', category: 'Semiconductor' },
  { symbol: 'NXPI', name: 'NXP Semiconductors', category: 'Semiconductor' },
  { symbol: 'SWKS', name: 'Skyworks Solutions', category: 'Semiconductor' },
  { symbol: 'MCHP', name: 'Microchip Technology', category: 'Semiconductor' },
  { symbol: 'STM', name: 'STMicroelectronics', category: 'Semiconductor' },
  { symbol: 'ADI', name: 'Analog Devices', category: 'Semiconductor' },
  { symbol: 'TER', name: 'Teradyne', category: 'Semiconductor' },

  { symbol: 'AAPL', name: 'Apple', category: 'Tech' },
  { symbol: 'AMZN', name: 'Amazon', category: 'Tech' },
  { symbol: 'ORCL', name: 'Oracle', category: 'Tech' },
  { symbol: 'CSCO', name: 'Cisco Systems', category: 'Tech' },
  { symbol: 'IBM', name: 'IBM', category: 'Tech' },
  { symbol: 'SAP', name: 'SAP', category: 'Tech' },
  { symbol: 'INTU', name: 'Intuit', category: 'Tech' },
  { symbol: 'UBER', name: 'Uber Technologies', category: 'Tech' },
  { symbol: 'SHOP', name: 'Shopify', category: 'Tech' },
  { symbol: 'NFLX', name: 'Netflix', category: 'Tech' },
  { symbol: 'PYPL', name: 'PayPal', category: 'Tech' },
  { symbol: 'SQ', name: 'Block', category: 'Tech' },
  { symbol: 'ABNB', name: 'Airbnb', category: 'Tech' },
  { symbol: 'DOCU', name: 'DocuSign', category: 'Tech' },
  { symbol: 'ZM', name: 'Zoom Communications', category: 'Tech' },
  { symbol: 'TEAM', name: 'Atlassian', category: 'Tech' },
  { symbol: 'WDAY', name: 'Workday', category: 'Tech' },
  { symbol: 'PANW', name: 'Palo Alto Networks', category: 'Tech' },
  { symbol: 'CRWD', name: 'CrowdStrike', category: 'Tech' },
  { symbol: 'ZS', name: 'Zscaler', category: 'Tech' },
  { symbol: 'DDOG', name: 'Datadog', category: 'Tech' },
  { symbol: 'NET', name: 'Cloudflare', category: 'Tech' },
  { symbol: 'MDB', name: 'MongoDB', category: 'Tech' },
  { symbol: 'TTD', name: 'The Trade Desk', category: 'Tech' },
  { symbol: 'HUBS', name: 'HubSpot', category: 'Tech' },
  { symbol: 'OKTA', name: 'Okta', category: 'Tech' },
  { symbol: 'TWLO', name: 'Twilio', category: 'Tech' },
  { symbol: 'ANET', name: 'Arista Networks', category: 'Tech' },
  { symbol: 'FTNT', name: 'Fortinet', category: 'Tech' },
  { symbol: 'VRSN', name: 'VeriSign', category: 'Tech' },
]
